version: "3.4"

services:
  workoutsapi:
    image: "jorjooo/workouts-api"
    build:
      context: ./WorkoutsAPI
      dockerfile: Dockerfile
    container_name: WorkoutsAPI
    ports:
      - "8081:80"

    depends_on:
      - database

  database:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    ports:
      - "1401:1433"
    container_name: "WorkoutsDB"
    hostname: "WorkoutsDB"
    environment:
      MSSQL_SA_PASSWORD: "S3cur3P@ssW0rd!"
      ACCEPT_EULA: "Y"
    volumes:
      - "./WorkoutsAPI/mssql/data:/var/opt/mssql/data"
      - "./WorkoutsAPI/mssql/log:/var/opt/mssql/log"
      - "./WorkoutsAPI/mssql/secrets:/var/opt/mssql/secrets"

  measurements-api:
    image: "jorjooo/measurements-api"
    build:
      context: ./MeasurementsAPI
      dockerfile: Dockerfile
    container_name: MeasurementsAPI
    ports:
      - "8083:80"
    depends_on:
      - measurements-database

  measurements-database:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    ports:
      - "1402:1433"
    container_name: "MeasurementsDB"
    hostname: "MeasurementsDB"
    environment:
      MSSQL_SA_PASSWORD: "S3cur3P@ssW0rd!"
      ACCEPT_EULA: "Y"
    volumes:
      - "./MeasurementsAPI/mssql/data:/var/opt/mssql/data"
      - "./MeasurementsAPI/mssql/log:/var/opt/mssql/log"
      - "./MeasurementsAPI/mssql/secrets:/var/opt/mssql/secrets"

  meals-api:
    image: "jorjooo/meals-api"
    build:
      context: ./MealsAPI
      dockerfile: Dockerfile
    container_name: MealsAPI
    ports:
      - "8085:80"
    depends_on:
      - meals-database

  meals-database:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    ports:
      - "1403:1433"
    container_name: "MealsDB"
    hostname: "MealsDB"
    environment:
      MSSQL_SA_PASSWORD: "S3cur3P@ssW0rd!"
      ACCEPT_EULA: "Y"
    volumes:
      - "./MealsAPI/mssql/data:/var/opt/mssql/data"
      - "./MealsAPI/mssql/log:/var/opt/mssql/log"
      - "./MealsAPI/mssql/secrets:/var/opt/mssql/secrets"

  dashboard-api:
    image: "jorjooo/dashboard-api"
    build:
      context: ./DashboardAPI
      dockerfile: Dockerfile
    container_name: DashboardAPI
    ports:
      - "8087:80"
    depends_on:
      - meals-database
      - measurements-database
      - database
      - redis
    environment:
      WAIT_HOSTS: database:1433, meals-database:1433, measurements-database:1433
      WAIT_TIMEOUT: 300
      WAIT_BEFORE: 15

  redis:
    image: "redis"
    ports:
      - "6379:6379"

  frontend:
    image: "jorjooo/fitness-track-frontend"
    container_name: "FitnessTrackFrontend"
    ports:
      - "80:80"
      - "443:443"
