version: "3.4"

services:
  workoutsapi:
    image: jorjooo/workouts-api
    #image: containerimageregistry.azurecr.io/workouts-api:latest
    container_name: workouts-api
    ports:
      - "8081:8081"
    depends_on:
      - database
    domainname: "fitness-track"

  database:
    image: mcr.microsoft.com/mssql/server:2022-latest
    user: "0"
    ports:
      - "1433:1433"
    container_name: workouts-database
    hostname: "workouts-db"
    environment:
      MSSQL_SA_PASSWORD: "S3cur3PassW0rd!"
      ACCEPT_EULA: "Y"
    volumes:
      # - workouts-data:/var/opt/mssql/data
      # - workouts-log:/var/opt/mssql/log
      # - workouts-secrets:/var/opt/mssql/secrets
      - "./WorkoutsAPI/mssql/data:/var/opt/mssql/data"
      - "./WorkoutsAPI/mssql/log:/var/opt/mssql/log"
      - "./WorkoutsAPI/mssql/secrets:/var/opt/mssql/secrets"

  measurements-api:
    image: jorjooo/measurements-api
    #image: containerimageregistry.azurecr.io/measurements-api:latest
    build:
      context: ./MeasurementsAPI
      dockerfile: Dockerfile
    container_name: measurements-api
    ports:
      - "8083:80"
    depends_on:
      - measurements-database

  measurements-database:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    user: "0"
    ports:
      - "1402:1433"
    container_name: measurements-database
    hostname: "measurements-db"
    environment:
      MSSQL_SA_PASSWORD: "S3cur3P@ssW0rd!"
      ACCEPT_EULA: "Y"
    volumes:
      # - measurements-data:/var/opt/mssql/data
      # - measurements-log:/var/opt/mssql/log
      # - measurements-secrets:/var/opt/mssql/secrets
      - "./MeasurementsAPI/mssql/data:/var/opt/mssql/data"
      - "./MeasurementsAPI/mssql/log:/var/opt/mssql/log"
      - "./MeasurementsAPI/mssql/secrets:/var/opt/mssql/secrets"

  meals-api:
    image: jorjooo/meals-api
    #image: containerimageregistry.azurecr.io/meals-api:latest
    build:
      context: ./MealsAPI
      dockerfile: Dockerfile
    container_name: meals-api
    ports:
      - "8085:80"
    depends_on:
      - meals-database

  meals-database:
    image: mcr.microsoft.com/mssql/server:2022-latest
    user: "0"
    ports:
      - "1403:1433"
    container_name: meals-database
    hostname: "meals-db"
    environment:
      MSSQL_SA_PASSWORD: "S3cur3P@ssW0rd!"
      ACCEPT_EULA: "Y"
    volumes:
      # - meals-data:/var/opt/mssql/data
      # - meals-log:/var/opt/mssql/log
      # - meals-secrets:/var/opt/mssql/secrets
      - "./MealsAPI/mssql/data:/var/opt/mssql/data"
      - "./MealsAPI/mssql/log:/var/opt/mssql/log"
      - "./MealsAPI/mssql/secrets:/var/opt/mssql/secrets"

  dashboard-api:
    image: jorjooo/dashboard-api
    #image: containerimageregistry.azurecr.io/dashboard-api:latest
    build:
      context: ./DashboardAPI
      dockerfile: Dockerfile
    container_name: dashboard-api
    ports:
      - "8087:80"
    depends_on:
      - meals-database
      - measurements-database
      - database
      - redis
    environment:
      WAIT_HOSTS: database:1433, meals-database:1433, measurements-database:1433, redis:6379
      WAIT_TIMEOUT: 300
      WAIT_BEFORE: 15

  redis:
    image: registry.hub.docker.com/library/redis:latest
    ports:
      - "6379:6379"

  frontend:
    image: jorjooo/fitness-track-frontend
    #image: containerimageregistry.azurecr.io/fitness-track-frontend:latest
    container_name: fitness-track-frontend
    ports:
      - "80:80"
      - "443:443"
    domainname: "fitness-track"
