// <auto-generated />
using System;
using MeasurementsAPI.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MeasurementsAPI.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20230404222847_GenerateMeasurements")]
    partial class GenerateMeasurements
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MeasurementsAPI.Models.Measurement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Value")
                        .HasColumnType("float");

                    b.Property<string>("applicationUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Measurements");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateTime(2023, 4, 3, 23, 28, 47, 854, DateTimeKind.Local).AddTicks(8078),
                            Type = "Weight",
                            Unit = "kg",
                            Value = 80.0,
                            applicationUserId = "620eebc4-69c6-48c1-b9bc-8ceb6855b607"
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateTime(2023, 4, 2, 23, 28, 47, 854, DateTimeKind.Local).AddTicks(8126),
                            Type = "Weight",
                            Unit = "kg",
                            Value = 83.0,
                            applicationUserId = "620eebc4-69c6-48c1-b9bc-8ceb6855b607"
                        },
                        new
                        {
                            Id = 3,
                            Date = new DateTime(2023, 4, 1, 23, 28, 47, 854, DateTimeKind.Local).AddTicks(8129),
                            Type = "Weight",
                            Unit = "kg",
                            Value = 83.0,
                            applicationUserId = "620eebc4-69c6-48c1-b9bc-8ceb6855b607"
                        },
                        new
                        {
                            Id = 4,
                            Date = new DateTime(2023, 3, 31, 23, 28, 47, 854, DateTimeKind.Local).AddTicks(8131),
                            Type = "Weight",
                            Unit = "kg",
                            Value = 80.0,
                            applicationUserId = "620eebc4-69c6-48c1-b9bc-8ceb6855b607"
                        },
                        new
                        {
                            Id = 5,
                            Date = new DateTime(2023, 3, 30, 23, 28, 47, 854, DateTimeKind.Local).AddTicks(8133),
                            Type = "Weight",
                            Unit = "kg",
                            Value = 83.0,
                            applicationUserId = "620eebc4-69c6-48c1-b9bc-8ceb6855b607"
                        },
                        new
                        {
                            Id = 6,
                            Date = new DateTime(2023, 3, 29, 23, 28, 47, 854, DateTimeKind.Local).AddTicks(8137),
                            Type = "Weight",
                            Unit = "kg",
                            Value = 80.0,
                            applicationUserId = "620eebc4-69c6-48c1-b9bc-8ceb6855b607"
                        },
                        new
                        {
                            Id = 7,
                            Date = new DateTime(2023, 3, 28, 23, 28, 47, 854, DateTimeKind.Local).AddTicks(8139),
                            Type = "Weight",
                            Unit = "kg",
                            Value = 86.0,
                            applicationUserId = "620eebc4-69c6-48c1-b9bc-8ceb6855b607"
                        },
                        new
                        {
                            Id = 8,
                            Date = new DateTime(2023, 3, 27, 23, 28, 47, 854, DateTimeKind.Local).AddTicks(8141),
                            Type = "Weight",
                            Unit = "kg",
                            Value = 84.0,
                            applicationUserId = "620eebc4-69c6-48c1-b9bc-8ceb6855b607"
                        },
                        new
                        {
                            Id = 9,
                            Date = new DateTime(2023, 3, 26, 23, 28, 47, 854, DateTimeKind.Local).AddTicks(8143),
                            Type = "Weight",
                            Unit = "kg",
                            Value = 83.0,
                            applicationUserId = "620eebc4-69c6-48c1-b9bc-8ceb6855b607"
                        },
                        new
                        {
                            Id = 10,
                            Date = new DateTime(2023, 3, 25, 23, 28, 47, 854, DateTimeKind.Local).AddTicks(8146),
                            Type = "Weight",
                            Unit = "kg",
                            Value = 85.0,
                            applicationUserId = "620eebc4-69c6-48c1-b9bc-8ceb6855b607"
                        },
                        new
                        {
                            Id = 11,
                            Date = new DateTime(2023, 3, 24, 23, 28, 47, 854, DateTimeKind.Local).AddTicks(8149),
                            Type = "Weight",
                            Unit = "kg",
                            Value = 86.0,
                            applicationUserId = "620eebc4-69c6-48c1-b9bc-8ceb6855b607"
                        },
                        new
                        {
                            Id = 12,
                            Date = new DateTime(2023, 3, 23, 23, 28, 47, 854, DateTimeKind.Local).AddTicks(8151),
                            Type = "Weight",
                            Unit = "kg",
                            Value = 83.0,
                            applicationUserId = "620eebc4-69c6-48c1-b9bc-8ceb6855b607"
                        },
                        new
                        {
                            Id = 13,
                            Date = new DateTime(2023, 3, 22, 23, 28, 47, 854, DateTimeKind.Local).AddTicks(8153),
                            Type = "Weight",
                            Unit = "kg",
                            Value = 83.0,
                            applicationUserId = "620eebc4-69c6-48c1-b9bc-8ceb6855b607"
                        },
                        new
                        {
                            Id = 14,
                            Date = new DateTime(2023, 3, 21, 23, 28, 47, 854, DateTimeKind.Local).AddTicks(8155),
                            Type = "Weight",
                            Unit = "kg",
                            Value = 84.0,
                            applicationUserId = "620eebc4-69c6-48c1-b9bc-8ceb6855b607"
                        },
                        new
                        {
                            Id = 15,
                            Date = new DateTime(2023, 4, 3, 23, 28, 47, 854, DateTimeKind.Local).AddTicks(8158),
                            Type = "Weight",
                            Unit = "kg",
                            Value = 84.0,
                            applicationUserId = "9bb8263a-6dd1-42e9-8f29-a847dbb3e059"
                        },
                        new
                        {
                            Id = 16,
                            Date = new DateTime(2023, 4, 2, 23, 28, 47, 854, DateTimeKind.Local).AddTicks(8161),
                            Type = "Weight",
                            Unit = "kg",
                            Value = 80.0,
                            applicationUserId = "9bb8263a-6dd1-42e9-8f29-a847dbb3e059"
                        },
                        new
                        {
                            Id = 17,
                            Date = new DateTime(2023, 4, 1, 23, 28, 47, 854, DateTimeKind.Local).AddTicks(8163),
                            Type = "Weight",
                            Unit = "kg",
                            Value = 82.0,
                            applicationUserId = "9bb8263a-6dd1-42e9-8f29-a847dbb3e059"
                        },
                        new
                        {
                            Id = 18,
                            Date = new DateTime(2023, 3, 31, 23, 28, 47, 854, DateTimeKind.Local).AddTicks(8166),
                            Type = "Weight",
                            Unit = "kg",
                            Value = 84.0,
                            applicationUserId = "9bb8263a-6dd1-42e9-8f29-a847dbb3e059"
                        },
                        new
                        {
                            Id = 19,
                            Date = new DateTime(2023, 3, 30, 23, 28, 47, 854, DateTimeKind.Local).AddTicks(8168),
                            Type = "Weight",
                            Unit = "kg",
                            Value = 86.0,
                            applicationUserId = "9bb8263a-6dd1-42e9-8f29-a847dbb3e059"
                        },
                        new
                        {
                            Id = 20,
                            Date = new DateTime(2023, 3, 29, 23, 28, 47, 854, DateTimeKind.Local).AddTicks(8170),
                            Type = "Weight",
                            Unit = "kg",
                            Value = 81.0,
                            applicationUserId = "9bb8263a-6dd1-42e9-8f29-a847dbb3e059"
                        },
                        new
                        {
                            Id = 21,
                            Date = new DateTime(2023, 3, 28, 23, 28, 47, 854, DateTimeKind.Local).AddTicks(8172),
                            Type = "Weight",
                            Unit = "kg",
                            Value = 84.0,
                            applicationUserId = "9bb8263a-6dd1-42e9-8f29-a847dbb3e059"
                        },
                        new
                        {
                            Id = 22,
                            Date = new DateTime(2023, 3, 27, 23, 28, 47, 854, DateTimeKind.Local).AddTicks(8175),
                            Type = "Weight",
                            Unit = "kg",
                            Value = 85.0,
                            applicationUserId = "9bb8263a-6dd1-42e9-8f29-a847dbb3e059"
                        },
                        new
                        {
                            Id = 23,
                            Date = new DateTime(2023, 3, 26, 23, 28, 47, 854, DateTimeKind.Local).AddTicks(8177),
                            Type = "Weight",
                            Unit = "kg",
                            Value = 84.0,
                            applicationUserId = "9bb8263a-6dd1-42e9-8f29-a847dbb3e059"
                        },
                        new
                        {
                            Id = 24,
                            Date = new DateTime(2023, 3, 25, 23, 28, 47, 854, DateTimeKind.Local).AddTicks(8179),
                            Type = "Weight",
                            Unit = "kg",
                            Value = 84.0,
                            applicationUserId = "9bb8263a-6dd1-42e9-8f29-a847dbb3e059"
                        },
                        new
                        {
                            Id = 25,
                            Date = new DateTime(2023, 3, 24, 23, 28, 47, 854, DateTimeKind.Local).AddTicks(8181),
                            Type = "Weight",
                            Unit = "kg",
                            Value = 80.0,
                            applicationUserId = "9bb8263a-6dd1-42e9-8f29-a847dbb3e059"
                        },
                        new
                        {
                            Id = 26,
                            Date = new DateTime(2023, 3, 23, 23, 28, 47, 854, DateTimeKind.Local).AddTicks(8183),
                            Type = "Weight",
                            Unit = "kg",
                            Value = 81.0,
                            applicationUserId = "9bb8263a-6dd1-42e9-8f29-a847dbb3e059"
                        },
                        new
                        {
                            Id = 27,
                            Date = new DateTime(2023, 3, 22, 23, 28, 47, 854, DateTimeKind.Local).AddTicks(8186),
                            Type = "Weight",
                            Unit = "kg",
                            Value = 80.0,
                            applicationUserId = "9bb8263a-6dd1-42e9-8f29-a847dbb3e059"
                        },
                        new
                        {
                            Id = 28,
                            Date = new DateTime(2023, 3, 21, 23, 28, 47, 854, DateTimeKind.Local).AddTicks(8188),
                            Type = "Weight",
                            Unit = "kg",
                            Value = 80.0,
                            applicationUserId = "9bb8263a-6dd1-42e9-8f29-a847dbb3e059"
                        },
                        new
                        {
                            Id = 29,
                            Date = new DateTime(2023, 4, 3, 23, 28, 47, 854, DateTimeKind.Local).AddTicks(8190),
                            Type = "Weight",
                            Unit = "kg",
                            Value = 80.0,
                            applicationUserId = "0371f684-9a41-4d40-ba2b-62cc5eabed46"
                        },
                        new
                        {
                            Id = 30,
                            Date = new DateTime(2023, 4, 2, 23, 28, 47, 854, DateTimeKind.Local).AddTicks(8193),
                            Type = "Weight",
                            Unit = "kg",
                            Value = 83.0,
                            applicationUserId = "0371f684-9a41-4d40-ba2b-62cc5eabed46"
                        },
                        new
                        {
                            Id = 31,
                            Date = new DateTime(2023, 4, 1, 23, 28, 47, 854, DateTimeKind.Local).AddTicks(8195),
                            Type = "Weight",
                            Unit = "kg",
                            Value = 84.0,
                            applicationUserId = "0371f684-9a41-4d40-ba2b-62cc5eabed46"
                        },
                        new
                        {
                            Id = 32,
                            Date = new DateTime(2023, 3, 31, 23, 28, 47, 854, DateTimeKind.Local).AddTicks(8197),
                            Type = "Weight",
                            Unit = "kg",
                            Value = 84.0,
                            applicationUserId = "0371f684-9a41-4d40-ba2b-62cc5eabed46"
                        },
                        new
                        {
                            Id = 33,
                            Date = new DateTime(2023, 3, 30, 23, 28, 47, 854, DateTimeKind.Local).AddTicks(8199),
                            Type = "Weight",
                            Unit = "kg",
                            Value = 86.0,
                            applicationUserId = "0371f684-9a41-4d40-ba2b-62cc5eabed46"
                        },
                        new
                        {
                            Id = 34,
                            Date = new DateTime(2023, 3, 29, 23, 28, 47, 854, DateTimeKind.Local).AddTicks(8202),
                            Type = "Weight",
                            Unit = "kg",
                            Value = 85.0,
                            applicationUserId = "0371f684-9a41-4d40-ba2b-62cc5eabed46"
                        },
                        new
                        {
                            Id = 35,
                            Date = new DateTime(2023, 3, 28, 23, 28, 47, 854, DateTimeKind.Local).AddTicks(8204),
                            Type = "Weight",
                            Unit = "kg",
                            Value = 82.0,
                            applicationUserId = "0371f684-9a41-4d40-ba2b-62cc5eabed46"
                        },
                        new
                        {
                            Id = 36,
                            Date = new DateTime(2023, 3, 27, 23, 28, 47, 854, DateTimeKind.Local).AddTicks(8206),
                            Type = "Weight",
                            Unit = "kg",
                            Value = 82.0,
                            applicationUserId = "0371f684-9a41-4d40-ba2b-62cc5eabed46"
                        },
                        new
                        {
                            Id = 37,
                            Date = new DateTime(2023, 3, 26, 23, 28, 47, 854, DateTimeKind.Local).AddTicks(8209),
                            Type = "Weight",
                            Unit = "kg",
                            Value = 80.0,
                            applicationUserId = "0371f684-9a41-4d40-ba2b-62cc5eabed46"
                        },
                        new
                        {
                            Id = 38,
                            Date = new DateTime(2023, 3, 25, 23, 28, 47, 854, DateTimeKind.Local).AddTicks(8211),
                            Type = "Weight",
                            Unit = "kg",
                            Value = 82.0,
                            applicationUserId = "0371f684-9a41-4d40-ba2b-62cc5eabed46"
                        },
                        new
                        {
                            Id = 39,
                            Date = new DateTime(2023, 3, 24, 23, 28, 47, 854, DateTimeKind.Local).AddTicks(8213),
                            Type = "Weight",
                            Unit = "kg",
                            Value = 86.0,
                            applicationUserId = "0371f684-9a41-4d40-ba2b-62cc5eabed46"
                        },
                        new
                        {
                            Id = 40,
                            Date = new DateTime(2023, 3, 23, 23, 28, 47, 854, DateTimeKind.Local).AddTicks(8215),
                            Type = "Weight",
                            Unit = "kg",
                            Value = 86.0,
                            applicationUserId = "0371f684-9a41-4d40-ba2b-62cc5eabed46"
                        },
                        new
                        {
                            Id = 41,
                            Date = new DateTime(2023, 3, 22, 23, 28, 47, 854, DateTimeKind.Local).AddTicks(8217),
                            Type = "Weight",
                            Unit = "kg",
                            Value = 84.0,
                            applicationUserId = "0371f684-9a41-4d40-ba2b-62cc5eabed46"
                        },
                        new
                        {
                            Id = 42,
                            Date = new DateTime(2023, 3, 21, 23, 28, 47, 854, DateTimeKind.Local).AddTicks(8220),
                            Type = "Weight",
                            Unit = "kg",
                            Value = 81.0,
                            applicationUserId = "0371f684-9a41-4d40-ba2b-62cc5eabed46"
                        },
                        new
                        {
                            Id = 43,
                            Date = new DateTime(2023, 4, 3, 23, 28, 47, 854, DateTimeKind.Local).AddTicks(8222),
                            Type = "Weight",
                            Unit = "kg",
                            Value = 85.0,
                            applicationUserId = "b2f2a636-d75c-48cf-8e01-e6f86ba36d4b"
                        },
                        new
                        {
                            Id = 44,
                            Date = new DateTime(2023, 4, 2, 23, 28, 47, 854, DateTimeKind.Local).AddTicks(8224),
                            Type = "Weight",
                            Unit = "kg",
                            Value = 81.0,
                            applicationUserId = "b2f2a636-d75c-48cf-8e01-e6f86ba36d4b"
                        },
                        new
                        {
                            Id = 45,
                            Date = new DateTime(2023, 4, 1, 23, 28, 47, 854, DateTimeKind.Local).AddTicks(8227),
                            Type = "Weight",
                            Unit = "kg",
                            Value = 86.0,
                            applicationUserId = "b2f2a636-d75c-48cf-8e01-e6f86ba36d4b"
                        },
                        new
                        {
                            Id = 46,
                            Date = new DateTime(2023, 3, 31, 23, 28, 47, 854, DateTimeKind.Local).AddTicks(8229),
                            Type = "Weight",
                            Unit = "kg",
                            Value = 80.0,
                            applicationUserId = "b2f2a636-d75c-48cf-8e01-e6f86ba36d4b"
                        },
                        new
                        {
                            Id = 47,
                            Date = new DateTime(2023, 3, 30, 23, 28, 47, 854, DateTimeKind.Local).AddTicks(8231),
                            Type = "Weight",
                            Unit = "kg",
                            Value = 85.0,
                            applicationUserId = "b2f2a636-d75c-48cf-8e01-e6f86ba36d4b"
                        },
                        new
                        {
                            Id = 48,
                            Date = new DateTime(2023, 3, 29, 23, 28, 47, 854, DateTimeKind.Local).AddTicks(8234),
                            Type = "Weight",
                            Unit = "kg",
                            Value = 84.0,
                            applicationUserId = "b2f2a636-d75c-48cf-8e01-e6f86ba36d4b"
                        },
                        new
                        {
                            Id = 49,
                            Date = new DateTime(2023, 3, 28, 23, 28, 47, 854, DateTimeKind.Local).AddTicks(8236),
                            Type = "Weight",
                            Unit = "kg",
                            Value = 84.0,
                            applicationUserId = "b2f2a636-d75c-48cf-8e01-e6f86ba36d4b"
                        },
                        new
                        {
                            Id = 50,
                            Date = new DateTime(2023, 3, 27, 23, 28, 47, 854, DateTimeKind.Local).AddTicks(8238),
                            Type = "Weight",
                            Unit = "kg",
                            Value = 80.0,
                            applicationUserId = "b2f2a636-d75c-48cf-8e01-e6f86ba36d4b"
                        },
                        new
                        {
                            Id = 51,
                            Date = new DateTime(2023, 3, 26, 23, 28, 47, 854, DateTimeKind.Local).AddTicks(8240),
                            Type = "Weight",
                            Unit = "kg",
                            Value = 85.0,
                            applicationUserId = "b2f2a636-d75c-48cf-8e01-e6f86ba36d4b"
                        },
                        new
                        {
                            Id = 52,
                            Date = new DateTime(2023, 3, 25, 23, 28, 47, 854, DateTimeKind.Local).AddTicks(8242),
                            Type = "Weight",
                            Unit = "kg",
                            Value = 86.0,
                            applicationUserId = "b2f2a636-d75c-48cf-8e01-e6f86ba36d4b"
                        },
                        new
                        {
                            Id = 53,
                            Date = new DateTime(2023, 3, 24, 23, 28, 47, 854, DateTimeKind.Local).AddTicks(8245),
                            Type = "Weight",
                            Unit = "kg",
                            Value = 80.0,
                            applicationUserId = "b2f2a636-d75c-48cf-8e01-e6f86ba36d4b"
                        },
                        new
                        {
                            Id = 54,
                            Date = new DateTime(2023, 3, 23, 23, 28, 47, 854, DateTimeKind.Local).AddTicks(8247),
                            Type = "Weight",
                            Unit = "kg",
                            Value = 80.0,
                            applicationUserId = "b2f2a636-d75c-48cf-8e01-e6f86ba36d4b"
                        },
                        new
                        {
                            Id = 55,
                            Date = new DateTime(2023, 3, 22, 23, 28, 47, 854, DateTimeKind.Local).AddTicks(8249),
                            Type = "Weight",
                            Unit = "kg",
                            Value = 84.0,
                            applicationUserId = "b2f2a636-d75c-48cf-8e01-e6f86ba36d4b"
                        },
                        new
                        {
                            Id = 56,
                            Date = new DateTime(2023, 3, 21, 23, 28, 47, 854, DateTimeKind.Local).AddTicks(8251),
                            Type = "Weight",
                            Unit = "kg",
                            Value = 80.0,
                            applicationUserId = "b2f2a636-d75c-48cf-8e01-e6f86ba36d4b"
                        },
                        new
                        {
                            Id = 57,
                            Date = new DateTime(2023, 4, 3, 23, 28, 47, 854, DateTimeKind.Local).AddTicks(8254),
                            Type = "Weight",
                            Unit = "kg",
                            Value = 85.0,
                            applicationUserId = "aa88aabd-677b-4588-8cb0-213d5ba9e660"
                        },
                        new
                        {
                            Id = 58,
                            Date = new DateTime(2023, 4, 2, 23, 28, 47, 854, DateTimeKind.Local).AddTicks(8256),
                            Type = "Weight",
                            Unit = "kg",
                            Value = 83.0,
                            applicationUserId = "aa88aabd-677b-4588-8cb0-213d5ba9e660"
                        },
                        new
                        {
                            Id = 59,
                            Date = new DateTime(2023, 4, 1, 23, 28, 47, 854, DateTimeKind.Local).AddTicks(8259),
                            Type = "Weight",
                            Unit = "kg",
                            Value = 86.0,
                            applicationUserId = "aa88aabd-677b-4588-8cb0-213d5ba9e660"
                        },
                        new
                        {
                            Id = 60,
                            Date = new DateTime(2023, 3, 31, 23, 28, 47, 854, DateTimeKind.Local).AddTicks(8261),
                            Type = "Weight",
                            Unit = "kg",
                            Value = 81.0,
                            applicationUserId = "aa88aabd-677b-4588-8cb0-213d5ba9e660"
                        },
                        new
                        {
                            Id = 61,
                            Date = new DateTime(2023, 3, 30, 23, 28, 47, 854, DateTimeKind.Local).AddTicks(8263),
                            Type = "Weight",
                            Unit = "kg",
                            Value = 82.0,
                            applicationUserId = "aa88aabd-677b-4588-8cb0-213d5ba9e660"
                        },
                        new
                        {
                            Id = 62,
                            Date = new DateTime(2023, 3, 29, 23, 28, 47, 854, DateTimeKind.Local).AddTicks(8265),
                            Type = "Weight",
                            Unit = "kg",
                            Value = 83.0,
                            applicationUserId = "aa88aabd-677b-4588-8cb0-213d5ba9e660"
                        },
                        new
                        {
                            Id = 63,
                            Date = new DateTime(2023, 3, 28, 23, 28, 47, 854, DateTimeKind.Local).AddTicks(8268),
                            Type = "Weight",
                            Unit = "kg",
                            Value = 85.0,
                            applicationUserId = "aa88aabd-677b-4588-8cb0-213d5ba9e660"
                        },
                        new
                        {
                            Id = 64,
                            Date = new DateTime(2023, 3, 27, 23, 28, 47, 854, DateTimeKind.Local).AddTicks(8309),
                            Type = "Weight",
                            Unit = "kg",
                            Value = 85.0,
                            applicationUserId = "aa88aabd-677b-4588-8cb0-213d5ba9e660"
                        },
                        new
                        {
                            Id = 65,
                            Date = new DateTime(2023, 3, 26, 23, 28, 47, 854, DateTimeKind.Local).AddTicks(8312),
                            Type = "Weight",
                            Unit = "kg",
                            Value = 81.0,
                            applicationUserId = "aa88aabd-677b-4588-8cb0-213d5ba9e660"
                        },
                        new
                        {
                            Id = 66,
                            Date = new DateTime(2023, 3, 25, 23, 28, 47, 854, DateTimeKind.Local).AddTicks(8315),
                            Type = "Weight",
                            Unit = "kg",
                            Value = 84.0,
                            applicationUserId = "aa88aabd-677b-4588-8cb0-213d5ba9e660"
                        },
                        new
                        {
                            Id = 67,
                            Date = new DateTime(2023, 3, 24, 23, 28, 47, 854, DateTimeKind.Local).AddTicks(8318),
                            Type = "Weight",
                            Unit = "kg",
                            Value = 84.0,
                            applicationUserId = "aa88aabd-677b-4588-8cb0-213d5ba9e660"
                        },
                        new
                        {
                            Id = 68,
                            Date = new DateTime(2023, 3, 23, 23, 28, 47, 854, DateTimeKind.Local).AddTicks(8320),
                            Type = "Weight",
                            Unit = "kg",
                            Value = 82.0,
                            applicationUserId = "aa88aabd-677b-4588-8cb0-213d5ba9e660"
                        },
                        new
                        {
                            Id = 69,
                            Date = new DateTime(2023, 3, 22, 23, 28, 47, 854, DateTimeKind.Local).AddTicks(8322),
                            Type = "Weight",
                            Unit = "kg",
                            Value = 84.0,
                            applicationUserId = "aa88aabd-677b-4588-8cb0-213d5ba9e660"
                        },
                        new
                        {
                            Id = 70,
                            Date = new DateTime(2023, 3, 21, 23, 28, 47, 854, DateTimeKind.Local).AddTicks(8324),
                            Type = "Weight",
                            Unit = "kg",
                            Value = 84.0,
                            applicationUserId = "aa88aabd-677b-4588-8cb0-213d5ba9e660"
                        },
                        new
                        {
                            Id = 71,
                            Date = new DateTime(2023, 4, 3, 23, 28, 47, 854, DateTimeKind.Local).AddTicks(8327),
                            Type = "Weight",
                            Unit = "kg",
                            Value = 84.0,
                            applicationUserId = "f0e37b93-0558-458c-9e61-d0330ed9f4ec"
                        },
                        new
                        {
                            Id = 72,
                            Date = new DateTime(2023, 4, 2, 23, 28, 47, 854, DateTimeKind.Local).AddTicks(8329),
                            Type = "Weight",
                            Unit = "kg",
                            Value = 83.0,
                            applicationUserId = "f0e37b93-0558-458c-9e61-d0330ed9f4ec"
                        },
                        new
                        {
                            Id = 73,
                            Date = new DateTime(2023, 4, 1, 23, 28, 47, 854, DateTimeKind.Local).AddTicks(8332),
                            Type = "Weight",
                            Unit = "kg",
                            Value = 81.0,
                            applicationUserId = "f0e37b93-0558-458c-9e61-d0330ed9f4ec"
                        },
                        new
                        {
                            Id = 74,
                            Date = new DateTime(2023, 3, 31, 23, 28, 47, 854, DateTimeKind.Local).AddTicks(8334),
                            Type = "Weight",
                            Unit = "kg",
                            Value = 83.0,
                            applicationUserId = "f0e37b93-0558-458c-9e61-d0330ed9f4ec"
                        },
                        new
                        {
                            Id = 75,
                            Date = new DateTime(2023, 3, 30, 23, 28, 47, 854, DateTimeKind.Local).AddTicks(8337),
                            Type = "Weight",
                            Unit = "kg",
                            Value = 80.0,
                            applicationUserId = "f0e37b93-0558-458c-9e61-d0330ed9f4ec"
                        },
                        new
                        {
                            Id = 76,
                            Date = new DateTime(2023, 3, 29, 23, 28, 47, 854, DateTimeKind.Local).AddTicks(8339),
                            Type = "Weight",
                            Unit = "kg",
                            Value = 86.0,
                            applicationUserId = "f0e37b93-0558-458c-9e61-d0330ed9f4ec"
                        },
                        new
                        {
                            Id = 77,
                            Date = new DateTime(2023, 3, 28, 23, 28, 47, 854, DateTimeKind.Local).AddTicks(8341),
                            Type = "Weight",
                            Unit = "kg",
                            Value = 81.0,
                            applicationUserId = "f0e37b93-0558-458c-9e61-d0330ed9f4ec"
                        },
                        new
                        {
                            Id = 78,
                            Date = new DateTime(2023, 3, 27, 23, 28, 47, 854, DateTimeKind.Local).AddTicks(8344),
                            Type = "Weight",
                            Unit = "kg",
                            Value = 84.0,
                            applicationUserId = "f0e37b93-0558-458c-9e61-d0330ed9f4ec"
                        },
                        new
                        {
                            Id = 79,
                            Date = new DateTime(2023, 3, 26, 23, 28, 47, 854, DateTimeKind.Local).AddTicks(8346),
                            Type = "Weight",
                            Unit = "kg",
                            Value = 83.0,
                            applicationUserId = "f0e37b93-0558-458c-9e61-d0330ed9f4ec"
                        },
                        new
                        {
                            Id = 80,
                            Date = new DateTime(2023, 3, 25, 23, 28, 47, 854, DateTimeKind.Local).AddTicks(8348),
                            Type = "Weight",
                            Unit = "kg",
                            Value = 83.0,
                            applicationUserId = "f0e37b93-0558-458c-9e61-d0330ed9f4ec"
                        },
                        new
                        {
                            Id = 81,
                            Date = new DateTime(2023, 3, 24, 23, 28, 47, 854, DateTimeKind.Local).AddTicks(8351),
                            Type = "Weight",
                            Unit = "kg",
                            Value = 85.0,
                            applicationUserId = "f0e37b93-0558-458c-9e61-d0330ed9f4ec"
                        },
                        new
                        {
                            Id = 82,
                            Date = new DateTime(2023, 3, 23, 23, 28, 47, 854, DateTimeKind.Local).AddTicks(8353),
                            Type = "Weight",
                            Unit = "kg",
                            Value = 83.0,
                            applicationUserId = "f0e37b93-0558-458c-9e61-d0330ed9f4ec"
                        },
                        new
                        {
                            Id = 83,
                            Date = new DateTime(2023, 3, 22, 23, 28, 47, 854, DateTimeKind.Local).AddTicks(8355),
                            Type = "Weight",
                            Unit = "kg",
                            Value = 83.0,
                            applicationUserId = "f0e37b93-0558-458c-9e61-d0330ed9f4ec"
                        },
                        new
                        {
                            Id = 84,
                            Date = new DateTime(2023, 3, 21, 23, 28, 47, 854, DateTimeKind.Local).AddTicks(8357),
                            Type = "Weight",
                            Unit = "kg",
                            Value = 80.0,
                            applicationUserId = "f0e37b93-0558-458c-9e61-d0330ed9f4ec"
                        },
                        new
                        {
                            Id = 85,
                            Date = new DateTime(2023, 4, 3, 23, 28, 47, 854, DateTimeKind.Local).AddTicks(8360),
                            Type = "Weight",
                            Unit = "kg",
                            Value = 83.0,
                            applicationUserId = "4d0bafc4-1d88-4433-9769-1e2d251530a7"
                        },
                        new
                        {
                            Id = 86,
                            Date = new DateTime(2023, 4, 2, 23, 28, 47, 854, DateTimeKind.Local).AddTicks(8362),
                            Type = "Weight",
                            Unit = "kg",
                            Value = 80.0,
                            applicationUserId = "4d0bafc4-1d88-4433-9769-1e2d251530a7"
                        },
                        new
                        {
                            Id = 87,
                            Date = new DateTime(2023, 4, 1, 23, 28, 47, 854, DateTimeKind.Local).AddTicks(8365),
                            Type = "Weight",
                            Unit = "kg",
                            Value = 85.0,
                            applicationUserId = "4d0bafc4-1d88-4433-9769-1e2d251530a7"
                        },
                        new
                        {
                            Id = 88,
                            Date = new DateTime(2023, 3, 31, 23, 28, 47, 854, DateTimeKind.Local).AddTicks(8367),
                            Type = "Weight",
                            Unit = "kg",
                            Value = 81.0,
                            applicationUserId = "4d0bafc4-1d88-4433-9769-1e2d251530a7"
                        },
                        new
                        {
                            Id = 89,
                            Date = new DateTime(2023, 3, 30, 23, 28, 47, 854, DateTimeKind.Local).AddTicks(8369),
                            Type = "Weight",
                            Unit = "kg",
                            Value = 85.0,
                            applicationUserId = "4d0bafc4-1d88-4433-9769-1e2d251530a7"
                        },
                        new
                        {
                            Id = 90,
                            Date = new DateTime(2023, 3, 29, 23, 28, 47, 854, DateTimeKind.Local).AddTicks(8372),
                            Type = "Weight",
                            Unit = "kg",
                            Value = 84.0,
                            applicationUserId = "4d0bafc4-1d88-4433-9769-1e2d251530a7"
                        },
                        new
                        {
                            Id = 91,
                            Date = new DateTime(2023, 3, 28, 23, 28, 47, 854, DateTimeKind.Local).AddTicks(8374),
                            Type = "Weight",
                            Unit = "kg",
                            Value = 82.0,
                            applicationUserId = "4d0bafc4-1d88-4433-9769-1e2d251530a7"
                        },
                        new
                        {
                            Id = 92,
                            Date = new DateTime(2023, 3, 27, 23, 28, 47, 854, DateTimeKind.Local).AddTicks(8377),
                            Type = "Weight",
                            Unit = "kg",
                            Value = 81.0,
                            applicationUserId = "4d0bafc4-1d88-4433-9769-1e2d251530a7"
                        },
                        new
                        {
                            Id = 93,
                            Date = new DateTime(2023, 3, 26, 23, 28, 47, 854, DateTimeKind.Local).AddTicks(8379),
                            Type = "Weight",
                            Unit = "kg",
                            Value = 82.0,
                            applicationUserId = "4d0bafc4-1d88-4433-9769-1e2d251530a7"
                        },
                        new
                        {
                            Id = 94,
                            Date = new DateTime(2023, 3, 25, 23, 28, 47, 854, DateTimeKind.Local).AddTicks(8381),
                            Type = "Weight",
                            Unit = "kg",
                            Value = 81.0,
                            applicationUserId = "4d0bafc4-1d88-4433-9769-1e2d251530a7"
                        },
                        new
                        {
                            Id = 95,
                            Date = new DateTime(2023, 3, 24, 23, 28, 47, 854, DateTimeKind.Local).AddTicks(8384),
                            Type = "Weight",
                            Unit = "kg",
                            Value = 85.0,
                            applicationUserId = "4d0bafc4-1d88-4433-9769-1e2d251530a7"
                        },
                        new
                        {
                            Id = 96,
                            Date = new DateTime(2023, 3, 23, 23, 28, 47, 854, DateTimeKind.Local).AddTicks(8386),
                            Type = "Weight",
                            Unit = "kg",
                            Value = 81.0,
                            applicationUserId = "4d0bafc4-1d88-4433-9769-1e2d251530a7"
                        },
                        new
                        {
                            Id = 97,
                            Date = new DateTime(2023, 3, 22, 23, 28, 47, 854, DateTimeKind.Local).AddTicks(8388),
                            Type = "Weight",
                            Unit = "kg",
                            Value = 82.0,
                            applicationUserId = "4d0bafc4-1d88-4433-9769-1e2d251530a7"
                        },
                        new
                        {
                            Id = 98,
                            Date = new DateTime(2023, 3, 21, 23, 28, 47, 854, DateTimeKind.Local).AddTicks(8391),
                            Type = "Weight",
                            Unit = "kg",
                            Value = 83.0,
                            applicationUserId = "4d0bafc4-1d88-4433-9769-1e2d251530a7"
                        },
                        new
                        {
                            Id = 99,
                            Date = new DateTime(2023, 4, 3, 23, 28, 47, 854, DateTimeKind.Local).AddTicks(8393),
                            Type = "Weight",
                            Unit = "kg",
                            Value = 83.0,
                            applicationUserId = "5febdbbe-d537-430f-9ccb-b48f252d2d4e"
                        },
                        new
                        {
                            Id = 100,
                            Date = new DateTime(2023, 4, 2, 23, 28, 47, 854, DateTimeKind.Local).AddTicks(8396),
                            Type = "Weight",
                            Unit = "kg",
                            Value = 81.0,
                            applicationUserId = "5febdbbe-d537-430f-9ccb-b48f252d2d4e"
                        },
                        new
                        {
                            Id = 101,
                            Date = new DateTime(2023, 4, 1, 23, 28, 47, 854, DateTimeKind.Local).AddTicks(8398),
                            Type = "Weight",
                            Unit = "kg",
                            Value = 86.0,
                            applicationUserId = "5febdbbe-d537-430f-9ccb-b48f252d2d4e"
                        },
                        new
                        {
                            Id = 102,
                            Date = new DateTime(2023, 3, 31, 23, 28, 47, 854, DateTimeKind.Local).AddTicks(8400),
                            Type = "Weight",
                            Unit = "kg",
                            Value = 81.0,
                            applicationUserId = "5febdbbe-d537-430f-9ccb-b48f252d2d4e"
                        },
                        new
                        {
                            Id = 103,
                            Date = new DateTime(2023, 3, 30, 23, 28, 47, 854, DateTimeKind.Local).AddTicks(8403),
                            Type = "Weight",
                            Unit = "kg",
                            Value = 83.0,
                            applicationUserId = "5febdbbe-d537-430f-9ccb-b48f252d2d4e"
                        },
                        new
                        {
                            Id = 104,
                            Date = new DateTime(2023, 3, 29, 23, 28, 47, 854, DateTimeKind.Local).AddTicks(8405),
                            Type = "Weight",
                            Unit = "kg",
                            Value = 86.0,
                            applicationUserId = "5febdbbe-d537-430f-9ccb-b48f252d2d4e"
                        },
                        new
                        {
                            Id = 105,
                            Date = new DateTime(2023, 3, 28, 23, 28, 47, 854, DateTimeKind.Local).AddTicks(8408),
                            Type = "Weight",
                            Unit = "kg",
                            Value = 82.0,
                            applicationUserId = "5febdbbe-d537-430f-9ccb-b48f252d2d4e"
                        },
                        new
                        {
                            Id = 106,
                            Date = new DateTime(2023, 3, 27, 23, 28, 47, 854, DateTimeKind.Local).AddTicks(8410),
                            Type = "Weight",
                            Unit = "kg",
                            Value = 86.0,
                            applicationUserId = "5febdbbe-d537-430f-9ccb-b48f252d2d4e"
                        },
                        new
                        {
                            Id = 107,
                            Date = new DateTime(2023, 3, 26, 23, 28, 47, 854, DateTimeKind.Local).AddTicks(8413),
                            Type = "Weight",
                            Unit = "kg",
                            Value = 82.0,
                            applicationUserId = "5febdbbe-d537-430f-9ccb-b48f252d2d4e"
                        },
                        new
                        {
                            Id = 108,
                            Date = new DateTime(2023, 3, 25, 23, 28, 47, 854, DateTimeKind.Local).AddTicks(8415),
                            Type = "Weight",
                            Unit = "kg",
                            Value = 86.0,
                            applicationUserId = "5febdbbe-d537-430f-9ccb-b48f252d2d4e"
                        },
                        new
                        {
                            Id = 109,
                            Date = new DateTime(2023, 3, 24, 23, 28, 47, 854, DateTimeKind.Local).AddTicks(8418),
                            Type = "Weight",
                            Unit = "kg",
                            Value = 82.0,
                            applicationUserId = "5febdbbe-d537-430f-9ccb-b48f252d2d4e"
                        },
                        new
                        {
                            Id = 110,
                            Date = new DateTime(2023, 3, 23, 23, 28, 47, 854, DateTimeKind.Local).AddTicks(8420),
                            Type = "Weight",
                            Unit = "kg",
                            Value = 85.0,
                            applicationUserId = "5febdbbe-d537-430f-9ccb-b48f252d2d4e"
                        },
                        new
                        {
                            Id = 111,
                            Date = new DateTime(2023, 3, 22, 23, 28, 47, 854, DateTimeKind.Local).AddTicks(8423),
                            Type = "Weight",
                            Unit = "kg",
                            Value = 81.0,
                            applicationUserId = "5febdbbe-d537-430f-9ccb-b48f252d2d4e"
                        },
                        new
                        {
                            Id = 112,
                            Date = new DateTime(2023, 3, 21, 23, 28, 47, 854, DateTimeKind.Local).AddTicks(8425),
                            Type = "Weight",
                            Unit = "kg",
                            Value = 86.0,
                            applicationUserId = "5febdbbe-d537-430f-9ccb-b48f252d2d4e"
                        },
                        new
                        {
                            Id = 113,
                            Date = new DateTime(2023, 4, 3, 23, 28, 47, 854, DateTimeKind.Local).AddTicks(8428),
                            Type = "Weight",
                            Unit = "kg",
                            Value = 84.0,
                            applicationUserId = "c4824aab-c08f-4141-86c4-082fd8bbca8c"
                        },
                        new
                        {
                            Id = 114,
                            Date = new DateTime(2023, 4, 2, 23, 28, 47, 854, DateTimeKind.Local).AddTicks(8430),
                            Type = "Weight",
                            Unit = "kg",
                            Value = 85.0,
                            applicationUserId = "c4824aab-c08f-4141-86c4-082fd8bbca8c"
                        },
                        new
                        {
                            Id = 115,
                            Date = new DateTime(2023, 4, 1, 23, 28, 47, 854, DateTimeKind.Local).AddTicks(8433),
                            Type = "Weight",
                            Unit = "kg",
                            Value = 83.0,
                            applicationUserId = "c4824aab-c08f-4141-86c4-082fd8bbca8c"
                        },
                        new
                        {
                            Id = 116,
                            Date = new DateTime(2023, 3, 31, 23, 28, 47, 854, DateTimeKind.Local).AddTicks(8435),
                            Type = "Weight",
                            Unit = "kg",
                            Value = 83.0,
                            applicationUserId = "c4824aab-c08f-4141-86c4-082fd8bbca8c"
                        },
                        new
                        {
                            Id = 117,
                            Date = new DateTime(2023, 3, 30, 23, 28, 47, 854, DateTimeKind.Local).AddTicks(8438),
                            Type = "Weight",
                            Unit = "kg",
                            Value = 85.0,
                            applicationUserId = "c4824aab-c08f-4141-86c4-082fd8bbca8c"
                        },
                        new
                        {
                            Id = 118,
                            Date = new DateTime(2023, 3, 29, 23, 28, 47, 854, DateTimeKind.Local).AddTicks(8441),
                            Type = "Weight",
                            Unit = "kg",
                            Value = 81.0,
                            applicationUserId = "c4824aab-c08f-4141-86c4-082fd8bbca8c"
                        },
                        new
                        {
                            Id = 119,
                            Date = new DateTime(2023, 3, 28, 23, 28, 47, 854, DateTimeKind.Local).AddTicks(8443),
                            Type = "Weight",
                            Unit = "kg",
                            Value = 86.0,
                            applicationUserId = "c4824aab-c08f-4141-86c4-082fd8bbca8c"
                        },
                        new
                        {
                            Id = 120,
                            Date = new DateTime(2023, 3, 27, 23, 28, 47, 854, DateTimeKind.Local).AddTicks(8446),
                            Type = "Weight",
                            Unit = "kg",
                            Value = 80.0,
                            applicationUserId = "c4824aab-c08f-4141-86c4-082fd8bbca8c"
                        },
                        new
                        {
                            Id = 121,
                            Date = new DateTime(2023, 3, 26, 23, 28, 47, 854, DateTimeKind.Local).AddTicks(8448),
                            Type = "Weight",
                            Unit = "kg",
                            Value = 82.0,
                            applicationUserId = "c4824aab-c08f-4141-86c4-082fd8bbca8c"
                        },
                        new
                        {
                            Id = 122,
                            Date = new DateTime(2023, 3, 25, 23, 28, 47, 854, DateTimeKind.Local).AddTicks(8451),
                            Type = "Weight",
                            Unit = "kg",
                            Value = 80.0,
                            applicationUserId = "c4824aab-c08f-4141-86c4-082fd8bbca8c"
                        },
                        new
                        {
                            Id = 123,
                            Date = new DateTime(2023, 3, 24, 23, 28, 47, 854, DateTimeKind.Local).AddTicks(8453),
                            Type = "Weight",
                            Unit = "kg",
                            Value = 83.0,
                            applicationUserId = "c4824aab-c08f-4141-86c4-082fd8bbca8c"
                        },
                        new
                        {
                            Id = 124,
                            Date = new DateTime(2023, 3, 23, 23, 28, 47, 854, DateTimeKind.Local).AddTicks(8456),
                            Type = "Weight",
                            Unit = "kg",
                            Value = 85.0,
                            applicationUserId = "c4824aab-c08f-4141-86c4-082fd8bbca8c"
                        },
                        new
                        {
                            Id = 125,
                            Date = new DateTime(2023, 3, 22, 23, 28, 47, 854, DateTimeKind.Local).AddTicks(8458),
                            Type = "Weight",
                            Unit = "kg",
                            Value = 84.0,
                            applicationUserId = "c4824aab-c08f-4141-86c4-082fd8bbca8c"
                        },
                        new
                        {
                            Id = 126,
                            Date = new DateTime(2023, 3, 21, 23, 28, 47, 854, DateTimeKind.Local).AddTicks(8461),
                            Type = "Weight",
                            Unit = "kg",
                            Value = 80.0,
                            applicationUserId = "c4824aab-c08f-4141-86c4-082fd8bbca8c"
                        },
                        new
                        {
                            Id = 127,
                            Date = new DateTime(2023, 4, 3, 23, 28, 47, 854, DateTimeKind.Local).AddTicks(8463),
                            Type = "Weight",
                            Unit = "kg",
                            Value = 85.0,
                            applicationUserId = "2abf2679-ae98-456c-99ed-fe7ca2698c2e"
                        },
                        new
                        {
                            Id = 128,
                            Date = new DateTime(2023, 4, 2, 23, 28, 47, 854, DateTimeKind.Local).AddTicks(8466),
                            Type = "Weight",
                            Unit = "kg",
                            Value = 82.0,
                            applicationUserId = "2abf2679-ae98-456c-99ed-fe7ca2698c2e"
                        },
                        new
                        {
                            Id = 129,
                            Date = new DateTime(2023, 4, 1, 23, 28, 47, 854, DateTimeKind.Local).AddTicks(8468),
                            Type = "Weight",
                            Unit = "kg",
                            Value = 85.0,
                            applicationUserId = "2abf2679-ae98-456c-99ed-fe7ca2698c2e"
                        },
                        new
                        {
                            Id = 130,
                            Date = new DateTime(2023, 3, 31, 23, 28, 47, 854, DateTimeKind.Local).AddTicks(8472),
                            Type = "Weight",
                            Unit = "kg",
                            Value = 81.0,
                            applicationUserId = "2abf2679-ae98-456c-99ed-fe7ca2698c2e"
                        },
                        new
                        {
                            Id = 131,
                            Date = new DateTime(2023, 3, 30, 23, 28, 47, 854, DateTimeKind.Local).AddTicks(8475),
                            Type = "Weight",
                            Unit = "kg",
                            Value = 86.0,
                            applicationUserId = "2abf2679-ae98-456c-99ed-fe7ca2698c2e"
                        },
                        new
                        {
                            Id = 132,
                            Date = new DateTime(2023, 3, 29, 23, 28, 47, 854, DateTimeKind.Local).AddTicks(8477),
                            Type = "Weight",
                            Unit = "kg",
                            Value = 82.0,
                            applicationUserId = "2abf2679-ae98-456c-99ed-fe7ca2698c2e"
                        },
                        new
                        {
                            Id = 133,
                            Date = new DateTime(2023, 3, 28, 23, 28, 47, 854, DateTimeKind.Local).AddTicks(8480),
                            Type = "Weight",
                            Unit = "kg",
                            Value = 82.0,
                            applicationUserId = "2abf2679-ae98-456c-99ed-fe7ca2698c2e"
                        },
                        new
                        {
                            Id = 134,
                            Date = new DateTime(2023, 3, 27, 23, 28, 47, 854, DateTimeKind.Local).AddTicks(8515),
                            Type = "Weight",
                            Unit = "kg",
                            Value = 80.0,
                            applicationUserId = "2abf2679-ae98-456c-99ed-fe7ca2698c2e"
                        },
                        new
                        {
                            Id = 135,
                            Date = new DateTime(2023, 3, 26, 23, 28, 47, 854, DateTimeKind.Local).AddTicks(8517),
                            Type = "Weight",
                            Unit = "kg",
                            Value = 85.0,
                            applicationUserId = "2abf2679-ae98-456c-99ed-fe7ca2698c2e"
                        },
                        new
                        {
                            Id = 136,
                            Date = new DateTime(2023, 3, 25, 23, 28, 47, 854, DateTimeKind.Local).AddTicks(8520),
                            Type = "Weight",
                            Unit = "kg",
                            Value = 85.0,
                            applicationUserId = "2abf2679-ae98-456c-99ed-fe7ca2698c2e"
                        },
                        new
                        {
                            Id = 137,
                            Date = new DateTime(2023, 3, 24, 23, 28, 47, 854, DateTimeKind.Local).AddTicks(8523),
                            Type = "Weight",
                            Unit = "kg",
                            Value = 81.0,
                            applicationUserId = "2abf2679-ae98-456c-99ed-fe7ca2698c2e"
                        },
                        new
                        {
                            Id = 138,
                            Date = new DateTime(2023, 3, 23, 23, 28, 47, 854, DateTimeKind.Local).AddTicks(8525),
                            Type = "Weight",
                            Unit = "kg",
                            Value = 82.0,
                            applicationUserId = "2abf2679-ae98-456c-99ed-fe7ca2698c2e"
                        },
                        new
                        {
                            Id = 139,
                            Date = new DateTime(2023, 3, 22, 23, 28, 47, 854, DateTimeKind.Local).AddTicks(8528),
                            Type = "Weight",
                            Unit = "kg",
                            Value = 80.0,
                            applicationUserId = "2abf2679-ae98-456c-99ed-fe7ca2698c2e"
                        },
                        new
                        {
                            Id = 140,
                            Date = new DateTime(2023, 3, 21, 23, 28, 47, 854, DateTimeKind.Local).AddTicks(8530),
                            Type = "Weight",
                            Unit = "kg",
                            Value = 80.0,
                            applicationUserId = "2abf2679-ae98-456c-99ed-fe7ca2698c2e"
                        },
                        new
                        {
                            Id = 141,
                            Date = new DateTime(2023, 4, 3, 23, 28, 47, 854, DateTimeKind.Local).AddTicks(8533),
                            Type = "Weight",
                            Unit = "kg",
                            Value = 83.0,
                            applicationUserId = "5f9c85a5-0150-4a44-b5a8-e2bf0e72a6b1"
                        },
                        new
                        {
                            Id = 142,
                            Date = new DateTime(2023, 4, 2, 23, 28, 47, 854, DateTimeKind.Local).AddTicks(8536),
                            Type = "Weight",
                            Unit = "kg",
                            Value = 80.0,
                            applicationUserId = "5f9c85a5-0150-4a44-b5a8-e2bf0e72a6b1"
                        },
                        new
                        {
                            Id = 143,
                            Date = new DateTime(2023, 4, 1, 23, 28, 47, 854, DateTimeKind.Local).AddTicks(8538),
                            Type = "Weight",
                            Unit = "kg",
                            Value = 83.0,
                            applicationUserId = "5f9c85a5-0150-4a44-b5a8-e2bf0e72a6b1"
                        },
                        new
                        {
                            Id = 144,
                            Date = new DateTime(2023, 3, 31, 23, 28, 47, 854, DateTimeKind.Local).AddTicks(8541),
                            Type = "Weight",
                            Unit = "kg",
                            Value = 80.0,
                            applicationUserId = "5f9c85a5-0150-4a44-b5a8-e2bf0e72a6b1"
                        },
                        new
                        {
                            Id = 145,
                            Date = new DateTime(2023, 3, 30, 23, 28, 47, 854, DateTimeKind.Local).AddTicks(8543),
                            Type = "Weight",
                            Unit = "kg",
                            Value = 82.0,
                            applicationUserId = "5f9c85a5-0150-4a44-b5a8-e2bf0e72a6b1"
                        },
                        new
                        {
                            Id = 146,
                            Date = new DateTime(2023, 3, 29, 23, 28, 47, 854, DateTimeKind.Local).AddTicks(8546),
                            Type = "Weight",
                            Unit = "kg",
                            Value = 80.0,
                            applicationUserId = "5f9c85a5-0150-4a44-b5a8-e2bf0e72a6b1"
                        },
                        new
                        {
                            Id = 147,
                            Date = new DateTime(2023, 3, 28, 23, 28, 47, 854, DateTimeKind.Local).AddTicks(8549),
                            Type = "Weight",
                            Unit = "kg",
                            Value = 84.0,
                            applicationUserId = "5f9c85a5-0150-4a44-b5a8-e2bf0e72a6b1"
                        },
                        new
                        {
                            Id = 148,
                            Date = new DateTime(2023, 3, 27, 23, 28, 47, 854, DateTimeKind.Local).AddTicks(8551),
                            Type = "Weight",
                            Unit = "kg",
                            Value = 83.0,
                            applicationUserId = "5f9c85a5-0150-4a44-b5a8-e2bf0e72a6b1"
                        },
                        new
                        {
                            Id = 149,
                            Date = new DateTime(2023, 3, 26, 23, 28, 47, 854, DateTimeKind.Local).AddTicks(8554),
                            Type = "Weight",
                            Unit = "kg",
                            Value = 84.0,
                            applicationUserId = "5f9c85a5-0150-4a44-b5a8-e2bf0e72a6b1"
                        },
                        new
                        {
                            Id = 150,
                            Date = new DateTime(2023, 3, 25, 23, 28, 47, 854, DateTimeKind.Local).AddTicks(8556),
                            Type = "Weight",
                            Unit = "kg",
                            Value = 81.0,
                            applicationUserId = "5f9c85a5-0150-4a44-b5a8-e2bf0e72a6b1"
                        },
                        new
                        {
                            Id = 151,
                            Date = new DateTime(2023, 3, 24, 23, 28, 47, 854, DateTimeKind.Local).AddTicks(8559),
                            Type = "Weight",
                            Unit = "kg",
                            Value = 80.0,
                            applicationUserId = "5f9c85a5-0150-4a44-b5a8-e2bf0e72a6b1"
                        },
                        new
                        {
                            Id = 152,
                            Date = new DateTime(2023, 3, 23, 23, 28, 47, 854, DateTimeKind.Local).AddTicks(8561),
                            Type = "Weight",
                            Unit = "kg",
                            Value = 81.0,
                            applicationUserId = "5f9c85a5-0150-4a44-b5a8-e2bf0e72a6b1"
                        },
                        new
                        {
                            Id = 153,
                            Date = new DateTime(2023, 3, 22, 23, 28, 47, 854, DateTimeKind.Local).AddTicks(8564),
                            Type = "Weight",
                            Unit = "kg",
                            Value = 83.0,
                            applicationUserId = "5f9c85a5-0150-4a44-b5a8-e2bf0e72a6b1"
                        },
                        new
                        {
                            Id = 154,
                            Date = new DateTime(2023, 3, 21, 23, 28, 47, 854, DateTimeKind.Local).AddTicks(8566),
                            Type = "Weight",
                            Unit = "kg",
                            Value = 86.0,
                            applicationUserId = "5f9c85a5-0150-4a44-b5a8-e2bf0e72a6b1"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
