// <auto-generated />
using System;
using MealsAPI.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MealsAPI.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20230404222406_GenerateMeals")]
    partial class GenerateMeals
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MealsAPI.Models.Meal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Carbohydrates")
                        .HasColumnType("float");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<double>("Fats")
                        .HasColumnType("float");

                    b.Property<double>("Protein")
                        .HasColumnType("float");

                    b.Property<double>("TotalCalories")
                        .HasColumnType("float");

                    b.Property<string>("applicationUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Meals");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Carbohydrates = 139.0,
                            Category = "Breakfast",
                            Date = new DateTime(2023, 4, 3, 23, 24, 6, 354, DateTimeKind.Local).AddTicks(6940),
                            Fats = 47.0,
                            Protein = 141.0,
                            TotalCalories = 1996.0,
                            applicationUserId = "620eebc4-69c6-48c1-b9bc-8ceb6855b607"
                        },
                        new
                        {
                            Id = 2,
                            Carbohydrates = 167.0,
                            Category = "Breakfast",
                            Date = new DateTime(2023, 4, 2, 23, 24, 6, 354, DateTimeKind.Local).AddTicks(6989),
                            Fats = 34.0,
                            Protein = 120.0,
                            TotalCalories = 1515.0,
                            applicationUserId = "620eebc4-69c6-48c1-b9bc-8ceb6855b607"
                        },
                        new
                        {
                            Id = 3,
                            Carbohydrates = 167.0,
                            Category = "Breakfast",
                            Date = new DateTime(2023, 4, 1, 23, 24, 6, 354, DateTimeKind.Local).AddTicks(6991),
                            Fats = 35.0,
                            Protein = 144.0,
                            TotalCalories = 1738.0,
                            applicationUserId = "620eebc4-69c6-48c1-b9bc-8ceb6855b607"
                        },
                        new
                        {
                            Id = 4,
                            Carbohydrates = 170.0,
                            Category = "Breakfast",
                            Date = new DateTime(2023, 3, 31, 23, 24, 6, 354, DateTimeKind.Local).AddTicks(6994),
                            Fats = 47.0,
                            Protein = 121.0,
                            TotalCalories = 1523.0,
                            applicationUserId = "620eebc4-69c6-48c1-b9bc-8ceb6855b607"
                        },
                        new
                        {
                            Id = 5,
                            Carbohydrates = 133.0,
                            Category = "Breakfast",
                            Date = new DateTime(2023, 3, 30, 23, 24, 6, 354, DateTimeKind.Local).AddTicks(6996),
                            Fats = 34.0,
                            Protein = 136.0,
                            TotalCalories = 1418.0,
                            applicationUserId = "620eebc4-69c6-48c1-b9bc-8ceb6855b607"
                        },
                        new
                        {
                            Id = 6,
                            Carbohydrates = 155.0,
                            Category = "Breakfast",
                            Date = new DateTime(2023, 3, 29, 23, 24, 6, 354, DateTimeKind.Local).AddTicks(6999),
                            Fats = 33.0,
                            Protein = 118.0,
                            TotalCalories = 1495.0,
                            applicationUserId = "620eebc4-69c6-48c1-b9bc-8ceb6855b607"
                        },
                        new
                        {
                            Id = 7,
                            Carbohydrates = 159.0,
                            Category = "Breakfast",
                            Date = new DateTime(2023, 3, 28, 23, 24, 6, 354, DateTimeKind.Local).AddTicks(7042),
                            Fats = 42.0,
                            Protein = 101.0,
                            TotalCalories = 1849.0,
                            applicationUserId = "620eebc4-69c6-48c1-b9bc-8ceb6855b607"
                        },
                        new
                        {
                            Id = 8,
                            Carbohydrates = 168.0,
                            Category = "Breakfast",
                            Date = new DateTime(2023, 3, 27, 23, 24, 6, 354, DateTimeKind.Local).AddTicks(7045),
                            Fats = 41.0,
                            Protein = 100.0,
                            TotalCalories = 1753.0,
                            applicationUserId = "620eebc4-69c6-48c1-b9bc-8ceb6855b607"
                        },
                        new
                        {
                            Id = 9,
                            Carbohydrates = 160.0,
                            Category = "Breakfast",
                            Date = new DateTime(2023, 3, 26, 23, 24, 6, 354, DateTimeKind.Local).AddTicks(7047),
                            Fats = 37.0,
                            Protein = 136.0,
                            TotalCalories = 1848.0,
                            applicationUserId = "620eebc4-69c6-48c1-b9bc-8ceb6855b607"
                        },
                        new
                        {
                            Id = 10,
                            Carbohydrates = 153.0,
                            Category = "Breakfast",
                            Date = new DateTime(2023, 3, 25, 23, 24, 6, 354, DateTimeKind.Local).AddTicks(7050),
                            Fats = 30.0,
                            Protein = 102.0,
                            TotalCalories = 1970.0,
                            applicationUserId = "620eebc4-69c6-48c1-b9bc-8ceb6855b607"
                        },
                        new
                        {
                            Id = 11,
                            Carbohydrates = 177.0,
                            Category = "Breakfast",
                            Date = new DateTime(2023, 3, 24, 23, 24, 6, 354, DateTimeKind.Local).AddTicks(7053),
                            Fats = 42.0,
                            Protein = 128.0,
                            TotalCalories = 1411.0,
                            applicationUserId = "620eebc4-69c6-48c1-b9bc-8ceb6855b607"
                        },
                        new
                        {
                            Id = 12,
                            Carbohydrates = 175.0,
                            Category = "Breakfast",
                            Date = new DateTime(2023, 3, 23, 23, 24, 6, 354, DateTimeKind.Local).AddTicks(7055),
                            Fats = 45.0,
                            Protein = 129.0,
                            TotalCalories = 1909.0,
                            applicationUserId = "620eebc4-69c6-48c1-b9bc-8ceb6855b607"
                        },
                        new
                        {
                            Id = 13,
                            Carbohydrates = 148.0,
                            Category = "Breakfast",
                            Date = new DateTime(2023, 3, 22, 23, 24, 6, 354, DateTimeKind.Local).AddTicks(7058),
                            Fats = 40.0,
                            Protein = 101.0,
                            TotalCalories = 1854.0,
                            applicationUserId = "620eebc4-69c6-48c1-b9bc-8ceb6855b607"
                        },
                        new
                        {
                            Id = 14,
                            Carbohydrates = 134.0,
                            Category = "Breakfast",
                            Date = new DateTime(2023, 3, 21, 23, 24, 6, 354, DateTimeKind.Local).AddTicks(7060),
                            Fats = 40.0,
                            Protein = 122.0,
                            TotalCalories = 1952.0,
                            applicationUserId = "620eebc4-69c6-48c1-b9bc-8ceb6855b607"
                        },
                        new
                        {
                            Id = 15,
                            Carbohydrates = 156.0,
                            Category = "Breakfast",
                            Date = new DateTime(2023, 4, 3, 23, 24, 6, 354, DateTimeKind.Local).AddTicks(7064),
                            Fats = 40.0,
                            Protein = 112.0,
                            TotalCalories = 1468.0,
                            applicationUserId = "9bb8263a-6dd1-42e9-8f29-a847dbb3e059"
                        },
                        new
                        {
                            Id = 16,
                            Carbohydrates = 145.0,
                            Category = "Breakfast",
                            Date = new DateTime(2023, 4, 2, 23, 24, 6, 354, DateTimeKind.Local).AddTicks(7067),
                            Fats = 46.0,
                            Protein = 105.0,
                            TotalCalories = 1698.0,
                            applicationUserId = "9bb8263a-6dd1-42e9-8f29-a847dbb3e059"
                        },
                        new
                        {
                            Id = 17,
                            Carbohydrates = 130.0,
                            Category = "Breakfast",
                            Date = new DateTime(2023, 4, 1, 23, 24, 6, 354, DateTimeKind.Local).AddTicks(7069),
                            Fats = 43.0,
                            Protein = 124.0,
                            TotalCalories = 1824.0,
                            applicationUserId = "9bb8263a-6dd1-42e9-8f29-a847dbb3e059"
                        },
                        new
                        {
                            Id = 18,
                            Carbohydrates = 166.0,
                            Category = "Breakfast",
                            Date = new DateTime(2023, 3, 31, 23, 24, 6, 354, DateTimeKind.Local).AddTicks(7073),
                            Fats = 39.0,
                            Protein = 100.0,
                            TotalCalories = 1949.0,
                            applicationUserId = "9bb8263a-6dd1-42e9-8f29-a847dbb3e059"
                        },
                        new
                        {
                            Id = 19,
                            Carbohydrates = 156.0,
                            Category = "Breakfast",
                            Date = new DateTime(2023, 3, 30, 23, 24, 6, 354, DateTimeKind.Local).AddTicks(7076),
                            Fats = 48.0,
                            Protein = 132.0,
                            TotalCalories = 1810.0,
                            applicationUserId = "9bb8263a-6dd1-42e9-8f29-a847dbb3e059"
                        },
                        new
                        {
                            Id = 20,
                            Carbohydrates = 175.0,
                            Category = "Breakfast",
                            Date = new DateTime(2023, 3, 29, 23, 24, 6, 354, DateTimeKind.Local).AddTicks(7078),
                            Fats = 44.0,
                            Protein = 108.0,
                            TotalCalories = 1331.0,
                            applicationUserId = "9bb8263a-6dd1-42e9-8f29-a847dbb3e059"
                        },
                        new
                        {
                            Id = 21,
                            Carbohydrates = 142.0,
                            Category = "Breakfast",
                            Date = new DateTime(2023, 3, 28, 23, 24, 6, 354, DateTimeKind.Local).AddTicks(7081),
                            Fats = 33.0,
                            Protein = 101.0,
                            TotalCalories = 1736.0,
                            applicationUserId = "9bb8263a-6dd1-42e9-8f29-a847dbb3e059"
                        },
                        new
                        {
                            Id = 22,
                            Carbohydrates = 178.0,
                            Category = "Breakfast",
                            Date = new DateTime(2023, 3, 27, 23, 24, 6, 354, DateTimeKind.Local).AddTicks(7083),
                            Fats = 37.0,
                            Protein = 120.0,
                            TotalCalories = 1638.0,
                            applicationUserId = "9bb8263a-6dd1-42e9-8f29-a847dbb3e059"
                        },
                        new
                        {
                            Id = 23,
                            Carbohydrates = 169.0,
                            Category = "Breakfast",
                            Date = new DateTime(2023, 3, 26, 23, 24, 6, 354, DateTimeKind.Local).AddTicks(7086),
                            Fats = 42.0,
                            Protein = 109.0,
                            TotalCalories = 1591.0,
                            applicationUserId = "9bb8263a-6dd1-42e9-8f29-a847dbb3e059"
                        },
                        new
                        {
                            Id = 24,
                            Carbohydrates = 153.0,
                            Category = "Breakfast",
                            Date = new DateTime(2023, 3, 25, 23, 24, 6, 354, DateTimeKind.Local).AddTicks(7088),
                            Fats = 32.0,
                            Protein = 128.0,
                            TotalCalories = 1805.0,
                            applicationUserId = "9bb8263a-6dd1-42e9-8f29-a847dbb3e059"
                        },
                        new
                        {
                            Id = 25,
                            Carbohydrates = 137.0,
                            Category = "Breakfast",
                            Date = new DateTime(2023, 3, 24, 23, 24, 6, 354, DateTimeKind.Local).AddTicks(7091),
                            Fats = 40.0,
                            Protein = 101.0,
                            TotalCalories = 1967.0,
                            applicationUserId = "9bb8263a-6dd1-42e9-8f29-a847dbb3e059"
                        },
                        new
                        {
                            Id = 26,
                            Carbohydrates = 170.0,
                            Category = "Breakfast",
                            Date = new DateTime(2023, 3, 23, 23, 24, 6, 354, DateTimeKind.Local).AddTicks(7093),
                            Fats = 49.0,
                            Protein = 133.0,
                            TotalCalories = 1717.0,
                            applicationUserId = "9bb8263a-6dd1-42e9-8f29-a847dbb3e059"
                        },
                        new
                        {
                            Id = 27,
                            Carbohydrates = 161.0,
                            Category = "Breakfast",
                            Date = new DateTime(2023, 3, 22, 23, 24, 6, 354, DateTimeKind.Local).AddTicks(7096),
                            Fats = 47.0,
                            Protein = 126.0,
                            TotalCalories = 1405.0,
                            applicationUserId = "9bb8263a-6dd1-42e9-8f29-a847dbb3e059"
                        },
                        new
                        {
                            Id = 28,
                            Carbohydrates = 148.0,
                            Category = "Breakfast",
                            Date = new DateTime(2023, 3, 21, 23, 24, 6, 354, DateTimeKind.Local).AddTicks(7098),
                            Fats = 41.0,
                            Protein = 113.0,
                            TotalCalories = 1616.0,
                            applicationUserId = "9bb8263a-6dd1-42e9-8f29-a847dbb3e059"
                        },
                        new
                        {
                            Id = 29,
                            Carbohydrates = 173.0,
                            Category = "Breakfast",
                            Date = new DateTime(2023, 4, 3, 23, 24, 6, 354, DateTimeKind.Local).AddTicks(7101),
                            Fats = 36.0,
                            Protein = 103.0,
                            TotalCalories = 1989.0,
                            applicationUserId = "0371f684-9a41-4d40-ba2b-62cc5eabed46"
                        },
                        new
                        {
                            Id = 30,
                            Carbohydrates = 135.0,
                            Category = "Breakfast",
                            Date = new DateTime(2023, 4, 2, 23, 24, 6, 354, DateTimeKind.Local).AddTicks(7104),
                            Fats = 32.0,
                            Protein = 101.0,
                            TotalCalories = 1433.0,
                            applicationUserId = "0371f684-9a41-4d40-ba2b-62cc5eabed46"
                        },
                        new
                        {
                            Id = 31,
                            Carbohydrates = 145.0,
                            Category = "Breakfast",
                            Date = new DateTime(2023, 4, 1, 23, 24, 6, 354, DateTimeKind.Local).AddTicks(7107),
                            Fats = 38.0,
                            Protein = 133.0,
                            TotalCalories = 1583.0,
                            applicationUserId = "0371f684-9a41-4d40-ba2b-62cc5eabed46"
                        },
                        new
                        {
                            Id = 32,
                            Carbohydrates = 143.0,
                            Category = "Breakfast",
                            Date = new DateTime(2023, 3, 31, 23, 24, 6, 354, DateTimeKind.Local).AddTicks(7110),
                            Fats = 44.0,
                            Protein = 101.0,
                            TotalCalories = 1795.0,
                            applicationUserId = "0371f684-9a41-4d40-ba2b-62cc5eabed46"
                        },
                        new
                        {
                            Id = 33,
                            Carbohydrates = 141.0,
                            Category = "Breakfast",
                            Date = new DateTime(2023, 3, 30, 23, 24, 6, 354, DateTimeKind.Local).AddTicks(7112),
                            Fats = 30.0,
                            Protein = 138.0,
                            TotalCalories = 1743.0,
                            applicationUserId = "0371f684-9a41-4d40-ba2b-62cc5eabed46"
                        },
                        new
                        {
                            Id = 34,
                            Carbohydrates = 132.0,
                            Category = "Breakfast",
                            Date = new DateTime(2023, 3, 29, 23, 24, 6, 354, DateTimeKind.Local).AddTicks(7115),
                            Fats = 45.0,
                            Protein = 130.0,
                            TotalCalories = 1984.0,
                            applicationUserId = "0371f684-9a41-4d40-ba2b-62cc5eabed46"
                        },
                        new
                        {
                            Id = 35,
                            Carbohydrates = 162.0,
                            Category = "Breakfast",
                            Date = new DateTime(2023, 3, 28, 23, 24, 6, 354, DateTimeKind.Local).AddTicks(7118),
                            Fats = 42.0,
                            Protein = 126.0,
                            TotalCalories = 1327.0,
                            applicationUserId = "0371f684-9a41-4d40-ba2b-62cc5eabed46"
                        },
                        new
                        {
                            Id = 36,
                            Carbohydrates = 178.0,
                            Category = "Breakfast",
                            Date = new DateTime(2023, 3, 27, 23, 24, 6, 354, DateTimeKind.Local).AddTicks(7120),
                            Fats = 30.0,
                            Protein = 143.0,
                            TotalCalories = 1351.0,
                            applicationUserId = "0371f684-9a41-4d40-ba2b-62cc5eabed46"
                        },
                        new
                        {
                            Id = 37,
                            Carbohydrates = 154.0,
                            Category = "Breakfast",
                            Date = new DateTime(2023, 3, 26, 23, 24, 6, 354, DateTimeKind.Local).AddTicks(7123),
                            Fats = 43.0,
                            Protein = 137.0,
                            TotalCalories = 1546.0,
                            applicationUserId = "0371f684-9a41-4d40-ba2b-62cc5eabed46"
                        },
                        new
                        {
                            Id = 38,
                            Carbohydrates = 156.0,
                            Category = "Breakfast",
                            Date = new DateTime(2023, 3, 25, 23, 24, 6, 354, DateTimeKind.Local).AddTicks(7125),
                            Fats = 39.0,
                            Protein = 106.0,
                            TotalCalories = 1661.0,
                            applicationUserId = "0371f684-9a41-4d40-ba2b-62cc5eabed46"
                        },
                        new
                        {
                            Id = 39,
                            Carbohydrates = 132.0,
                            Category = "Breakfast",
                            Date = new DateTime(2023, 3, 24, 23, 24, 6, 354, DateTimeKind.Local).AddTicks(7128),
                            Fats = 44.0,
                            Protein = 131.0,
                            TotalCalories = 1580.0,
                            applicationUserId = "0371f684-9a41-4d40-ba2b-62cc5eabed46"
                        },
                        new
                        {
                            Id = 40,
                            Carbohydrates = 169.0,
                            Category = "Breakfast",
                            Date = new DateTime(2023, 3, 23, 23, 24, 6, 354, DateTimeKind.Local).AddTicks(7130),
                            Fats = 44.0,
                            Protein = 120.0,
                            TotalCalories = 1484.0,
                            applicationUserId = "0371f684-9a41-4d40-ba2b-62cc5eabed46"
                        },
                        new
                        {
                            Id = 41,
                            Carbohydrates = 139.0,
                            Category = "Breakfast",
                            Date = new DateTime(2023, 3, 22, 23, 24, 6, 354, DateTimeKind.Local).AddTicks(7133),
                            Fats = 47.0,
                            Protein = 100.0,
                            TotalCalories = 1976.0,
                            applicationUserId = "0371f684-9a41-4d40-ba2b-62cc5eabed46"
                        },
                        new
                        {
                            Id = 42,
                            Carbohydrates = 137.0,
                            Category = "Breakfast",
                            Date = new DateTime(2023, 3, 21, 23, 24, 6, 354, DateTimeKind.Local).AddTicks(7136),
                            Fats = 40.0,
                            Protein = 128.0,
                            TotalCalories = 1860.0,
                            applicationUserId = "0371f684-9a41-4d40-ba2b-62cc5eabed46"
                        },
                        new
                        {
                            Id = 43,
                            Carbohydrates = 179.0,
                            Category = "Breakfast",
                            Date = new DateTime(2023, 4, 3, 23, 24, 6, 354, DateTimeKind.Local).AddTicks(7138),
                            Fats = 37.0,
                            Protein = 121.0,
                            TotalCalories = 1737.0,
                            applicationUserId = "b2f2a636-d75c-48cf-8e01-e6f86ba36d4b"
                        },
                        new
                        {
                            Id = 44,
                            Carbohydrates = 137.0,
                            Category = "Breakfast",
                            Date = new DateTime(2023, 4, 2, 23, 24, 6, 354, DateTimeKind.Local).AddTicks(7141),
                            Fats = 43.0,
                            Protein = 134.0,
                            TotalCalories = 1850.0,
                            applicationUserId = "b2f2a636-d75c-48cf-8e01-e6f86ba36d4b"
                        },
                        new
                        {
                            Id = 45,
                            Carbohydrates = 148.0,
                            Category = "Breakfast",
                            Date = new DateTime(2023, 4, 1, 23, 24, 6, 354, DateTimeKind.Local).AddTicks(7143),
                            Fats = 34.0,
                            Protein = 141.0,
                            TotalCalories = 1584.0,
                            applicationUserId = "b2f2a636-d75c-48cf-8e01-e6f86ba36d4b"
                        },
                        new
                        {
                            Id = 46,
                            Carbohydrates = 169.0,
                            Category = "Breakfast",
                            Date = new DateTime(2023, 3, 31, 23, 24, 6, 354, DateTimeKind.Local).AddTicks(7146),
                            Fats = 34.0,
                            Protein = 126.0,
                            TotalCalories = 1505.0,
                            applicationUserId = "b2f2a636-d75c-48cf-8e01-e6f86ba36d4b"
                        },
                        new
                        {
                            Id = 47,
                            Carbohydrates = 179.0,
                            Category = "Breakfast",
                            Date = new DateTime(2023, 3, 30, 23, 24, 6, 354, DateTimeKind.Local).AddTicks(7149),
                            Fats = 32.0,
                            Protein = 123.0,
                            TotalCalories = 1895.0,
                            applicationUserId = "b2f2a636-d75c-48cf-8e01-e6f86ba36d4b"
                        },
                        new
                        {
                            Id = 48,
                            Carbohydrates = 138.0,
                            Category = "Breakfast",
                            Date = new DateTime(2023, 3, 29, 23, 24, 6, 354, DateTimeKind.Local).AddTicks(7152),
                            Fats = 49.0,
                            Protein = 114.0,
                            TotalCalories = 1769.0,
                            applicationUserId = "b2f2a636-d75c-48cf-8e01-e6f86ba36d4b"
                        },
                        new
                        {
                            Id = 49,
                            Carbohydrates = 145.0,
                            Category = "Breakfast",
                            Date = new DateTime(2023, 3, 28, 23, 24, 6, 354, DateTimeKind.Local).AddTicks(7154),
                            Fats = 39.0,
                            Protein = 121.0,
                            TotalCalories = 1614.0,
                            applicationUserId = "b2f2a636-d75c-48cf-8e01-e6f86ba36d4b"
                        },
                        new
                        {
                            Id = 50,
                            Carbohydrates = 132.0,
                            Category = "Breakfast",
                            Date = new DateTime(2023, 3, 27, 23, 24, 6, 354, DateTimeKind.Local).AddTicks(7157),
                            Fats = 44.0,
                            Protein = 149.0,
                            TotalCalories = 1617.0,
                            applicationUserId = "b2f2a636-d75c-48cf-8e01-e6f86ba36d4b"
                        },
                        new
                        {
                            Id = 51,
                            Carbohydrates = 168.0,
                            Category = "Breakfast",
                            Date = new DateTime(2023, 3, 26, 23, 24, 6, 354, DateTimeKind.Local).AddTicks(7160),
                            Fats = 46.0,
                            Protein = 127.0,
                            TotalCalories = 1483.0,
                            applicationUserId = "b2f2a636-d75c-48cf-8e01-e6f86ba36d4b"
                        },
                        new
                        {
                            Id = 52,
                            Carbohydrates = 166.0,
                            Category = "Breakfast",
                            Date = new DateTime(2023, 3, 25, 23, 24, 6, 354, DateTimeKind.Local).AddTicks(7162),
                            Fats = 33.0,
                            Protein = 148.0,
                            TotalCalories = 1591.0,
                            applicationUserId = "b2f2a636-d75c-48cf-8e01-e6f86ba36d4b"
                        },
                        new
                        {
                            Id = 53,
                            Carbohydrates = 152.0,
                            Category = "Breakfast",
                            Date = new DateTime(2023, 3, 24, 23, 24, 6, 354, DateTimeKind.Local).AddTicks(7165),
                            Fats = 38.0,
                            Protein = 106.0,
                            TotalCalories = 1933.0,
                            applicationUserId = "b2f2a636-d75c-48cf-8e01-e6f86ba36d4b"
                        },
                        new
                        {
                            Id = 54,
                            Carbohydrates = 152.0,
                            Category = "Breakfast",
                            Date = new DateTime(2023, 3, 23, 23, 24, 6, 354, DateTimeKind.Local).AddTicks(7168),
                            Fats = 39.0,
                            Protein = 137.0,
                            TotalCalories = 1318.0,
                            applicationUserId = "b2f2a636-d75c-48cf-8e01-e6f86ba36d4b"
                        },
                        new
                        {
                            Id = 55,
                            Carbohydrates = 176.0,
                            Category = "Breakfast",
                            Date = new DateTime(2023, 3, 22, 23, 24, 6, 354, DateTimeKind.Local).AddTicks(7170),
                            Fats = 43.0,
                            Protein = 114.0,
                            TotalCalories = 1485.0,
                            applicationUserId = "b2f2a636-d75c-48cf-8e01-e6f86ba36d4b"
                        },
                        new
                        {
                            Id = 56,
                            Carbohydrates = 154.0,
                            Category = "Breakfast",
                            Date = new DateTime(2023, 3, 21, 23, 24, 6, 354, DateTimeKind.Local).AddTicks(7173),
                            Fats = 30.0,
                            Protein = 141.0,
                            TotalCalories = 1337.0,
                            applicationUserId = "b2f2a636-d75c-48cf-8e01-e6f86ba36d4b"
                        },
                        new
                        {
                            Id = 57,
                            Carbohydrates = 176.0,
                            Category = "Breakfast",
                            Date = new DateTime(2023, 4, 3, 23, 24, 6, 354, DateTimeKind.Local).AddTicks(7176),
                            Fats = 47.0,
                            Protein = 129.0,
                            TotalCalories = 1726.0,
                            applicationUserId = "aa88aabd-677b-4588-8cb0-213d5ba9e660"
                        },
                        new
                        {
                            Id = 58,
                            Carbohydrates = 154.0,
                            Category = "Breakfast",
                            Date = new DateTime(2023, 4, 2, 23, 24, 6, 354, DateTimeKind.Local).AddTicks(7179),
                            Fats = 38.0,
                            Protein = 118.0,
                            TotalCalories = 1491.0,
                            applicationUserId = "aa88aabd-677b-4588-8cb0-213d5ba9e660"
                        },
                        new
                        {
                            Id = 59,
                            Carbohydrates = 170.0,
                            Category = "Breakfast",
                            Date = new DateTime(2023, 4, 1, 23, 24, 6, 354, DateTimeKind.Local).AddTicks(7182),
                            Fats = 49.0,
                            Protein = 121.0,
                            TotalCalories = 1718.0,
                            applicationUserId = "aa88aabd-677b-4588-8cb0-213d5ba9e660"
                        },
                        new
                        {
                            Id = 60,
                            Carbohydrates = 166.0,
                            Category = "Breakfast",
                            Date = new DateTime(2023, 3, 31, 23, 24, 6, 354, DateTimeKind.Local).AddTicks(7184),
                            Fats = 49.0,
                            Protein = 105.0,
                            TotalCalories = 1599.0,
                            applicationUserId = "aa88aabd-677b-4588-8cb0-213d5ba9e660"
                        },
                        new
                        {
                            Id = 61,
                            Carbohydrates = 170.0,
                            Category = "Breakfast",
                            Date = new DateTime(2023, 3, 30, 23, 24, 6, 354, DateTimeKind.Local).AddTicks(7187),
                            Fats = 38.0,
                            Protein = 121.0,
                            TotalCalories = 1604.0,
                            applicationUserId = "aa88aabd-677b-4588-8cb0-213d5ba9e660"
                        },
                        new
                        {
                            Id = 62,
                            Carbohydrates = 136.0,
                            Category = "Breakfast",
                            Date = new DateTime(2023, 3, 29, 23, 24, 6, 354, DateTimeKind.Local).AddTicks(7189),
                            Fats = 30.0,
                            Protein = 119.0,
                            TotalCalories = 1515.0,
                            applicationUserId = "aa88aabd-677b-4588-8cb0-213d5ba9e660"
                        },
                        new
                        {
                            Id = 63,
                            Carbohydrates = 159.0,
                            Category = "Breakfast",
                            Date = new DateTime(2023, 3, 28, 23, 24, 6, 354, DateTimeKind.Local).AddTicks(7192),
                            Fats = 46.0,
                            Protein = 112.0,
                            TotalCalories = 1841.0,
                            applicationUserId = "aa88aabd-677b-4588-8cb0-213d5ba9e660"
                        },
                        new
                        {
                            Id = 64,
                            Carbohydrates = 135.0,
                            Category = "Breakfast",
                            Date = new DateTime(2023, 3, 27, 23, 24, 6, 354, DateTimeKind.Local).AddTicks(7195),
                            Fats = 41.0,
                            Protein = 105.0,
                            TotalCalories = 1745.0,
                            applicationUserId = "aa88aabd-677b-4588-8cb0-213d5ba9e660"
                        },
                        new
                        {
                            Id = 65,
                            Carbohydrates = 136.0,
                            Category = "Breakfast",
                            Date = new DateTime(2023, 3, 26, 23, 24, 6, 354, DateTimeKind.Local).AddTicks(7197),
                            Fats = 49.0,
                            Protein = 102.0,
                            TotalCalories = 1310.0,
                            applicationUserId = "aa88aabd-677b-4588-8cb0-213d5ba9e660"
                        },
                        new
                        {
                            Id = 66,
                            Carbohydrates = 143.0,
                            Category = "Breakfast",
                            Date = new DateTime(2023, 3, 25, 23, 24, 6, 354, DateTimeKind.Local).AddTicks(7201),
                            Fats = 36.0,
                            Protein = 117.0,
                            TotalCalories = 1606.0,
                            applicationUserId = "aa88aabd-677b-4588-8cb0-213d5ba9e660"
                        },
                        new
                        {
                            Id = 67,
                            Carbohydrates = 178.0,
                            Category = "Breakfast",
                            Date = new DateTime(2023, 3, 24, 23, 24, 6, 354, DateTimeKind.Local).AddTicks(7204),
                            Fats = 30.0,
                            Protein = 126.0,
                            TotalCalories = 1930.0,
                            applicationUserId = "aa88aabd-677b-4588-8cb0-213d5ba9e660"
                        },
                        new
                        {
                            Id = 68,
                            Carbohydrates = 167.0,
                            Category = "Breakfast",
                            Date = new DateTime(2023, 3, 23, 23, 24, 6, 354, DateTimeKind.Local).AddTicks(7207),
                            Fats = 49.0,
                            Protein = 124.0,
                            TotalCalories = 1675.0,
                            applicationUserId = "aa88aabd-677b-4588-8cb0-213d5ba9e660"
                        },
                        new
                        {
                            Id = 69,
                            Carbohydrates = 155.0,
                            Category = "Breakfast",
                            Date = new DateTime(2023, 3, 22, 23, 24, 6, 354, DateTimeKind.Local).AddTicks(7210),
                            Fats = 44.0,
                            Protein = 148.0,
                            TotalCalories = 1862.0,
                            applicationUserId = "aa88aabd-677b-4588-8cb0-213d5ba9e660"
                        },
                        new
                        {
                            Id = 70,
                            Carbohydrates = 130.0,
                            Category = "Breakfast",
                            Date = new DateTime(2023, 3, 21, 23, 24, 6, 354, DateTimeKind.Local).AddTicks(7212),
                            Fats = 47.0,
                            Protein = 141.0,
                            TotalCalories = 1760.0,
                            applicationUserId = "aa88aabd-677b-4588-8cb0-213d5ba9e660"
                        },
                        new
                        {
                            Id = 71,
                            Carbohydrates = 141.0,
                            Category = "Breakfast",
                            Date = new DateTime(2023, 4, 3, 23, 24, 6, 354, DateTimeKind.Local).AddTicks(7215),
                            Fats = 43.0,
                            Protein = 115.0,
                            TotalCalories = 1667.0,
                            applicationUserId = "f0e37b93-0558-458c-9e61-d0330ed9f4ec"
                        },
                        new
                        {
                            Id = 72,
                            Carbohydrates = 159.0,
                            Category = "Breakfast",
                            Date = new DateTime(2023, 4, 2, 23, 24, 6, 354, DateTimeKind.Local).AddTicks(7218),
                            Fats = 34.0,
                            Protein = 105.0,
                            TotalCalories = 1862.0,
                            applicationUserId = "f0e37b93-0558-458c-9e61-d0330ed9f4ec"
                        },
                        new
                        {
                            Id = 73,
                            Carbohydrates = 140.0,
                            Category = "Breakfast",
                            Date = new DateTime(2023, 4, 1, 23, 24, 6, 354, DateTimeKind.Local).AddTicks(7221),
                            Fats = 38.0,
                            Protein = 118.0,
                            TotalCalories = 1364.0,
                            applicationUserId = "f0e37b93-0558-458c-9e61-d0330ed9f4ec"
                        },
                        new
                        {
                            Id = 74,
                            Carbohydrates = 173.0,
                            Category = "Breakfast",
                            Date = new DateTime(2023, 3, 31, 23, 24, 6, 354, DateTimeKind.Local).AddTicks(7223),
                            Fats = 43.0,
                            Protein = 110.0,
                            TotalCalories = 1428.0,
                            applicationUserId = "f0e37b93-0558-458c-9e61-d0330ed9f4ec"
                        },
                        new
                        {
                            Id = 75,
                            Carbohydrates = 178.0,
                            Category = "Breakfast",
                            Date = new DateTime(2023, 3, 30, 23, 24, 6, 354, DateTimeKind.Local).AddTicks(7227),
                            Fats = 42.0,
                            Protein = 128.0,
                            TotalCalories = 1685.0,
                            applicationUserId = "f0e37b93-0558-458c-9e61-d0330ed9f4ec"
                        },
                        new
                        {
                            Id = 76,
                            Carbohydrates = 168.0,
                            Category = "Breakfast",
                            Date = new DateTime(2023, 3, 29, 23, 24, 6, 354, DateTimeKind.Local).AddTicks(7229),
                            Fats = 39.0,
                            Protein = 121.0,
                            TotalCalories = 1939.0,
                            applicationUserId = "f0e37b93-0558-458c-9e61-d0330ed9f4ec"
                        },
                        new
                        {
                            Id = 77,
                            Carbohydrates = 143.0,
                            Category = "Breakfast",
                            Date = new DateTime(2023, 3, 28, 23, 24, 6, 354, DateTimeKind.Local).AddTicks(7232),
                            Fats = 37.0,
                            Protein = 121.0,
                            TotalCalories = 1590.0,
                            applicationUserId = "f0e37b93-0558-458c-9e61-d0330ed9f4ec"
                        },
                        new
                        {
                            Id = 78,
                            Carbohydrates = 138.0,
                            Category = "Breakfast",
                            Date = new DateTime(2023, 3, 27, 23, 24, 6, 354, DateTimeKind.Local).AddTicks(7235),
                            Fats = 49.0,
                            Protein = 131.0,
                            TotalCalories = 1437.0,
                            applicationUserId = "f0e37b93-0558-458c-9e61-d0330ed9f4ec"
                        },
                        new
                        {
                            Id = 79,
                            Carbohydrates = 173.0,
                            Category = "Breakfast",
                            Date = new DateTime(2023, 3, 26, 23, 24, 6, 354, DateTimeKind.Local).AddTicks(7237),
                            Fats = 35.0,
                            Protein = 116.0,
                            TotalCalories = 1854.0,
                            applicationUserId = "f0e37b93-0558-458c-9e61-d0330ed9f4ec"
                        },
                        new
                        {
                            Id = 80,
                            Carbohydrates = 130.0,
                            Category = "Breakfast",
                            Date = new DateTime(2023, 3, 25, 23, 24, 6, 354, DateTimeKind.Local).AddTicks(7240),
                            Fats = 30.0,
                            Protein = 136.0,
                            TotalCalories = 1372.0,
                            applicationUserId = "f0e37b93-0558-458c-9e61-d0330ed9f4ec"
                        },
                        new
                        {
                            Id = 81,
                            Carbohydrates = 142.0,
                            Category = "Breakfast",
                            Date = new DateTime(2023, 3, 24, 23, 24, 6, 354, DateTimeKind.Local).AddTicks(7243),
                            Fats = 31.0,
                            Protein = 137.0,
                            TotalCalories = 1564.0,
                            applicationUserId = "f0e37b93-0558-458c-9e61-d0330ed9f4ec"
                        },
                        new
                        {
                            Id = 82,
                            Carbohydrates = 150.0,
                            Category = "Breakfast",
                            Date = new DateTime(2023, 3, 23, 23, 24, 6, 354, DateTimeKind.Local).AddTicks(7245),
                            Fats = 48.0,
                            Protein = 106.0,
                            TotalCalories = 1528.0,
                            applicationUserId = "f0e37b93-0558-458c-9e61-d0330ed9f4ec"
                        },
                        new
                        {
                            Id = 83,
                            Carbohydrates = 156.0,
                            Category = "Breakfast",
                            Date = new DateTime(2023, 3, 22, 23, 24, 6, 354, DateTimeKind.Local).AddTicks(7248),
                            Fats = 45.0,
                            Protein = 139.0,
                            TotalCalories = 1656.0,
                            applicationUserId = "f0e37b93-0558-458c-9e61-d0330ed9f4ec"
                        },
                        new
                        {
                            Id = 84,
                            Carbohydrates = 163.0,
                            Category = "Breakfast",
                            Date = new DateTime(2023, 3, 21, 23, 24, 6, 354, DateTimeKind.Local).AddTicks(7282),
                            Fats = 33.0,
                            Protein = 146.0,
                            TotalCalories = 1689.0,
                            applicationUserId = "f0e37b93-0558-458c-9e61-d0330ed9f4ec"
                        },
                        new
                        {
                            Id = 85,
                            Carbohydrates = 171.0,
                            Category = "Breakfast",
                            Date = new DateTime(2023, 4, 3, 23, 24, 6, 354, DateTimeKind.Local).AddTicks(7285),
                            Fats = 48.0,
                            Protein = 112.0,
                            TotalCalories = 1992.0,
                            applicationUserId = "4d0bafc4-1d88-4433-9769-1e2d251530a7"
                        },
                        new
                        {
                            Id = 86,
                            Carbohydrates = 150.0,
                            Category = "Breakfast",
                            Date = new DateTime(2023, 4, 2, 23, 24, 6, 354, DateTimeKind.Local).AddTicks(7288),
                            Fats = 31.0,
                            Protein = 101.0,
                            TotalCalories = 1886.0,
                            applicationUserId = "4d0bafc4-1d88-4433-9769-1e2d251530a7"
                        },
                        new
                        {
                            Id = 87,
                            Carbohydrates = 169.0,
                            Category = "Breakfast",
                            Date = new DateTime(2023, 4, 1, 23, 24, 6, 354, DateTimeKind.Local).AddTicks(7291),
                            Fats = 37.0,
                            Protein = 138.0,
                            TotalCalories = 1656.0,
                            applicationUserId = "4d0bafc4-1d88-4433-9769-1e2d251530a7"
                        },
                        new
                        {
                            Id = 88,
                            Carbohydrates = 133.0,
                            Category = "Breakfast",
                            Date = new DateTime(2023, 3, 31, 23, 24, 6, 354, DateTimeKind.Local).AddTicks(7294),
                            Fats = 47.0,
                            Protein = 139.0,
                            TotalCalories = 1415.0,
                            applicationUserId = "4d0bafc4-1d88-4433-9769-1e2d251530a7"
                        },
                        new
                        {
                            Id = 89,
                            Carbohydrates = 156.0,
                            Category = "Breakfast",
                            Date = new DateTime(2023, 3, 30, 23, 24, 6, 354, DateTimeKind.Local).AddTicks(7297),
                            Fats = 44.0,
                            Protein = 103.0,
                            TotalCalories = 1443.0,
                            applicationUserId = "4d0bafc4-1d88-4433-9769-1e2d251530a7"
                        },
                        new
                        {
                            Id = 90,
                            Carbohydrates = 144.0,
                            Category = "Breakfast",
                            Date = new DateTime(2023, 3, 29, 23, 24, 6, 354, DateTimeKind.Local).AddTicks(7300),
                            Fats = 49.0,
                            Protein = 119.0,
                            TotalCalories = 1868.0,
                            applicationUserId = "4d0bafc4-1d88-4433-9769-1e2d251530a7"
                        },
                        new
                        {
                            Id = 91,
                            Carbohydrates = 170.0,
                            Category = "Breakfast",
                            Date = new DateTime(2023, 3, 28, 23, 24, 6, 354, DateTimeKind.Local).AddTicks(7302),
                            Fats = 30.0,
                            Protein = 125.0,
                            TotalCalories = 1305.0,
                            applicationUserId = "4d0bafc4-1d88-4433-9769-1e2d251530a7"
                        },
                        new
                        {
                            Id = 92,
                            Carbohydrates = 178.0,
                            Category = "Breakfast",
                            Date = new DateTime(2023, 3, 27, 23, 24, 6, 354, DateTimeKind.Local).AddTicks(7305),
                            Fats = 47.0,
                            Protein = 134.0,
                            TotalCalories = 1565.0,
                            applicationUserId = "4d0bafc4-1d88-4433-9769-1e2d251530a7"
                        },
                        new
                        {
                            Id = 93,
                            Carbohydrates = 140.0,
                            Category = "Breakfast",
                            Date = new DateTime(2023, 3, 26, 23, 24, 6, 354, DateTimeKind.Local).AddTicks(7308),
                            Fats = 49.0,
                            Protein = 136.0,
                            TotalCalories = 1321.0,
                            applicationUserId = "4d0bafc4-1d88-4433-9769-1e2d251530a7"
                        },
                        new
                        {
                            Id = 94,
                            Carbohydrates = 152.0,
                            Category = "Breakfast",
                            Date = new DateTime(2023, 3, 25, 23, 24, 6, 354, DateTimeKind.Local).AddTicks(7310),
                            Fats = 42.0,
                            Protein = 111.0,
                            TotalCalories = 1377.0,
                            applicationUserId = "4d0bafc4-1d88-4433-9769-1e2d251530a7"
                        },
                        new
                        {
                            Id = 95,
                            Carbohydrates = 140.0,
                            Category = "Breakfast",
                            Date = new DateTime(2023, 3, 24, 23, 24, 6, 354, DateTimeKind.Local).AddTicks(7313),
                            Fats = 38.0,
                            Protein = 148.0,
                            TotalCalories = 1623.0,
                            applicationUserId = "4d0bafc4-1d88-4433-9769-1e2d251530a7"
                        },
                        new
                        {
                            Id = 96,
                            Carbohydrates = 163.0,
                            Category = "Breakfast",
                            Date = new DateTime(2023, 3, 23, 23, 24, 6, 354, DateTimeKind.Local).AddTicks(7316),
                            Fats = 39.0,
                            Protein = 141.0,
                            TotalCalories = 1702.0,
                            applicationUserId = "4d0bafc4-1d88-4433-9769-1e2d251530a7"
                        },
                        new
                        {
                            Id = 97,
                            Carbohydrates = 147.0,
                            Category = "Breakfast",
                            Date = new DateTime(2023, 3, 22, 23, 24, 6, 354, DateTimeKind.Local).AddTicks(7319),
                            Fats = 37.0,
                            Protein = 126.0,
                            TotalCalories = 1526.0,
                            applicationUserId = "4d0bafc4-1d88-4433-9769-1e2d251530a7"
                        },
                        new
                        {
                            Id = 98,
                            Carbohydrates = 175.0,
                            Category = "Breakfast",
                            Date = new DateTime(2023, 3, 21, 23, 24, 6, 354, DateTimeKind.Local).AddTicks(7321),
                            Fats = 46.0,
                            Protein = 130.0,
                            TotalCalories = 1982.0,
                            applicationUserId = "4d0bafc4-1d88-4433-9769-1e2d251530a7"
                        },
                        new
                        {
                            Id = 99,
                            Carbohydrates = 153.0,
                            Category = "Breakfast",
                            Date = new DateTime(2023, 4, 3, 23, 24, 6, 354, DateTimeKind.Local).AddTicks(7324),
                            Fats = 33.0,
                            Protein = 146.0,
                            TotalCalories = 1589.0,
                            applicationUserId = "5febdbbe-d537-430f-9ccb-b48f252d2d4e"
                        },
                        new
                        {
                            Id = 100,
                            Carbohydrates = 136.0,
                            Category = "Breakfast",
                            Date = new DateTime(2023, 4, 2, 23, 24, 6, 354, DateTimeKind.Local).AddTicks(7327),
                            Fats = 47.0,
                            Protein = 130.0,
                            TotalCalories = 1546.0,
                            applicationUserId = "5febdbbe-d537-430f-9ccb-b48f252d2d4e"
                        },
                        new
                        {
                            Id = 101,
                            Carbohydrates = 167.0,
                            Category = "Breakfast",
                            Date = new DateTime(2023, 4, 1, 23, 24, 6, 354, DateTimeKind.Local).AddTicks(7330),
                            Fats = 32.0,
                            Protein = 126.0,
                            TotalCalories = 1795.0,
                            applicationUserId = "5febdbbe-d537-430f-9ccb-b48f252d2d4e"
                        },
                        new
                        {
                            Id = 102,
                            Carbohydrates = 176.0,
                            Category = "Breakfast",
                            Date = new DateTime(2023, 3, 31, 23, 24, 6, 354, DateTimeKind.Local).AddTicks(7333),
                            Fats = 41.0,
                            Protein = 108.0,
                            TotalCalories = 1596.0,
                            applicationUserId = "5febdbbe-d537-430f-9ccb-b48f252d2d4e"
                        },
                        new
                        {
                            Id = 103,
                            Carbohydrates = 169.0,
                            Category = "Breakfast",
                            Date = new DateTime(2023, 3, 30, 23, 24, 6, 354, DateTimeKind.Local).AddTicks(7336),
                            Fats = 43.0,
                            Protein = 134.0,
                            TotalCalories = 1709.0,
                            applicationUserId = "5febdbbe-d537-430f-9ccb-b48f252d2d4e"
                        },
                        new
                        {
                            Id = 104,
                            Carbohydrates = 169.0,
                            Category = "Breakfast",
                            Date = new DateTime(2023, 3, 29, 23, 24, 6, 354, DateTimeKind.Local).AddTicks(7339),
                            Fats = 40.0,
                            Protein = 115.0,
                            TotalCalories = 1421.0,
                            applicationUserId = "5febdbbe-d537-430f-9ccb-b48f252d2d4e"
                        },
                        new
                        {
                            Id = 105,
                            Carbohydrates = 139.0,
                            Category = "Breakfast",
                            Date = new DateTime(2023, 3, 28, 23, 24, 6, 354, DateTimeKind.Local).AddTicks(7342),
                            Fats = 42.0,
                            Protein = 133.0,
                            TotalCalories = 1856.0,
                            applicationUserId = "5febdbbe-d537-430f-9ccb-b48f252d2d4e"
                        },
                        new
                        {
                            Id = 106,
                            Carbohydrates = 169.0,
                            Category = "Breakfast",
                            Date = new DateTime(2023, 3, 27, 23, 24, 6, 354, DateTimeKind.Local).AddTicks(7345),
                            Fats = 40.0,
                            Protein = 113.0,
                            TotalCalories = 1544.0,
                            applicationUserId = "5febdbbe-d537-430f-9ccb-b48f252d2d4e"
                        },
                        new
                        {
                            Id = 107,
                            Carbohydrates = 164.0,
                            Category = "Breakfast",
                            Date = new DateTime(2023, 3, 26, 23, 24, 6, 354, DateTimeKind.Local).AddTicks(7347),
                            Fats = 34.0,
                            Protein = 137.0,
                            TotalCalories = 1954.0,
                            applicationUserId = "5febdbbe-d537-430f-9ccb-b48f252d2d4e"
                        },
                        new
                        {
                            Id = 108,
                            Carbohydrates = 134.0,
                            Category = "Breakfast",
                            Date = new DateTime(2023, 3, 25, 23, 24, 6, 354, DateTimeKind.Local).AddTicks(7350),
                            Fats = 36.0,
                            Protein = 107.0,
                            TotalCalories = 1719.0,
                            applicationUserId = "5febdbbe-d537-430f-9ccb-b48f252d2d4e"
                        },
                        new
                        {
                            Id = 109,
                            Carbohydrates = 159.0,
                            Category = "Breakfast",
                            Date = new DateTime(2023, 3, 24, 23, 24, 6, 354, DateTimeKind.Local).AddTicks(7353),
                            Fats = 31.0,
                            Protein = 128.0,
                            TotalCalories = 1913.0,
                            applicationUserId = "5febdbbe-d537-430f-9ccb-b48f252d2d4e"
                        },
                        new
                        {
                            Id = 110,
                            Carbohydrates = 155.0,
                            Category = "Breakfast",
                            Date = new DateTime(2023, 3, 23, 23, 24, 6, 354, DateTimeKind.Local).AddTicks(7356),
                            Fats = 44.0,
                            Protein = 119.0,
                            TotalCalories = 1672.0,
                            applicationUserId = "5febdbbe-d537-430f-9ccb-b48f252d2d4e"
                        },
                        new
                        {
                            Id = 111,
                            Carbohydrates = 171.0,
                            Category = "Breakfast",
                            Date = new DateTime(2023, 3, 22, 23, 24, 6, 354, DateTimeKind.Local).AddTicks(7359),
                            Fats = 44.0,
                            Protein = 140.0,
                            TotalCalories = 1608.0,
                            applicationUserId = "5febdbbe-d537-430f-9ccb-b48f252d2d4e"
                        },
                        new
                        {
                            Id = 112,
                            Carbohydrates = 141.0,
                            Category = "Breakfast",
                            Date = new DateTime(2023, 3, 21, 23, 24, 6, 354, DateTimeKind.Local).AddTicks(7362),
                            Fats = 38.0,
                            Protein = 126.0,
                            TotalCalories = 1722.0,
                            applicationUserId = "5febdbbe-d537-430f-9ccb-b48f252d2d4e"
                        },
                        new
                        {
                            Id = 113,
                            Carbohydrates = 161.0,
                            Category = "Breakfast",
                            Date = new DateTime(2023, 4, 3, 23, 24, 6, 354, DateTimeKind.Local).AddTicks(7365),
                            Fats = 30.0,
                            Protein = 145.0,
                            TotalCalories = 1777.0,
                            applicationUserId = "c4824aab-c08f-4141-86c4-082fd8bbca8c"
                        },
                        new
                        {
                            Id = 114,
                            Carbohydrates = 158.0,
                            Category = "Breakfast",
                            Date = new DateTime(2023, 4, 2, 23, 24, 6, 354, DateTimeKind.Local).AddTicks(7368),
                            Fats = 38.0,
                            Protein = 106.0,
                            TotalCalories = 1849.0,
                            applicationUserId = "c4824aab-c08f-4141-86c4-082fd8bbca8c"
                        },
                        new
                        {
                            Id = 115,
                            Carbohydrates = 174.0,
                            Category = "Breakfast",
                            Date = new DateTime(2023, 4, 1, 23, 24, 6, 354, DateTimeKind.Local).AddTicks(7371),
                            Fats = 47.0,
                            Protein = 119.0,
                            TotalCalories = 1741.0,
                            applicationUserId = "c4824aab-c08f-4141-86c4-082fd8bbca8c"
                        },
                        new
                        {
                            Id = 116,
                            Carbohydrates = 153.0,
                            Category = "Breakfast",
                            Date = new DateTime(2023, 3, 31, 23, 24, 6, 354, DateTimeKind.Local).AddTicks(7374),
                            Fats = 43.0,
                            Protein = 149.0,
                            TotalCalories = 1589.0,
                            applicationUserId = "c4824aab-c08f-4141-86c4-082fd8bbca8c"
                        },
                        new
                        {
                            Id = 117,
                            Carbohydrates = 165.0,
                            Category = "Breakfast",
                            Date = new DateTime(2023, 3, 30, 23, 24, 6, 354, DateTimeKind.Local).AddTicks(7377),
                            Fats = 40.0,
                            Protein = 118.0,
                            TotalCalories = 1860.0,
                            applicationUserId = "c4824aab-c08f-4141-86c4-082fd8bbca8c"
                        },
                        new
                        {
                            Id = 118,
                            Carbohydrates = 150.0,
                            Category = "Breakfast",
                            Date = new DateTime(2023, 3, 29, 23, 24, 6, 354, DateTimeKind.Local).AddTicks(7380),
                            Fats = 42.0,
                            Protein = 141.0,
                            TotalCalories = 1639.0,
                            applicationUserId = "c4824aab-c08f-4141-86c4-082fd8bbca8c"
                        },
                        new
                        {
                            Id = 119,
                            Carbohydrates = 153.0,
                            Category = "Breakfast",
                            Date = new DateTime(2023, 3, 28, 23, 24, 6, 354, DateTimeKind.Local).AddTicks(7383),
                            Fats = 30.0,
                            Protein = 124.0,
                            TotalCalories = 1340.0,
                            applicationUserId = "c4824aab-c08f-4141-86c4-082fd8bbca8c"
                        },
                        new
                        {
                            Id = 120,
                            Carbohydrates = 138.0,
                            Category = "Breakfast",
                            Date = new DateTime(2023, 3, 27, 23, 24, 6, 354, DateTimeKind.Local).AddTicks(7386),
                            Fats = 33.0,
                            Protein = 114.0,
                            TotalCalories = 1938.0,
                            applicationUserId = "c4824aab-c08f-4141-86c4-082fd8bbca8c"
                        },
                        new
                        {
                            Id = 121,
                            Carbohydrates = 137.0,
                            Category = "Breakfast",
                            Date = new DateTime(2023, 3, 26, 23, 24, 6, 354, DateTimeKind.Local).AddTicks(7389),
                            Fats = 30.0,
                            Protein = 134.0,
                            TotalCalories = 1323.0,
                            applicationUserId = "c4824aab-c08f-4141-86c4-082fd8bbca8c"
                        },
                        new
                        {
                            Id = 122,
                            Carbohydrates = 149.0,
                            Category = "Breakfast",
                            Date = new DateTime(2023, 3, 25, 23, 24, 6, 354, DateTimeKind.Local).AddTicks(7392),
                            Fats = 38.0,
                            Protein = 115.0,
                            TotalCalories = 1938.0,
                            applicationUserId = "c4824aab-c08f-4141-86c4-082fd8bbca8c"
                        },
                        new
                        {
                            Id = 123,
                            Carbohydrates = 154.0,
                            Category = "Breakfast",
                            Date = new DateTime(2023, 3, 24, 23, 24, 6, 354, DateTimeKind.Local).AddTicks(7395),
                            Fats = 35.0,
                            Protein = 102.0,
                            TotalCalories = 1848.0,
                            applicationUserId = "c4824aab-c08f-4141-86c4-082fd8bbca8c"
                        },
                        new
                        {
                            Id = 124,
                            Carbohydrates = 133.0,
                            Category = "Breakfast",
                            Date = new DateTime(2023, 3, 23, 23, 24, 6, 354, DateTimeKind.Local).AddTicks(7398),
                            Fats = 37.0,
                            Protein = 128.0,
                            TotalCalories = 1672.0,
                            applicationUserId = "c4824aab-c08f-4141-86c4-082fd8bbca8c"
                        },
                        new
                        {
                            Id = 125,
                            Carbohydrates = 177.0,
                            Category = "Breakfast",
                            Date = new DateTime(2023, 3, 22, 23, 24, 6, 354, DateTimeKind.Local).AddTicks(7400),
                            Fats = 44.0,
                            Protein = 112.0,
                            TotalCalories = 1955.0,
                            applicationUserId = "c4824aab-c08f-4141-86c4-082fd8bbca8c"
                        },
                        new
                        {
                            Id = 126,
                            Carbohydrates = 132.0,
                            Category = "Breakfast",
                            Date = new DateTime(2023, 3, 21, 23, 24, 6, 354, DateTimeKind.Local).AddTicks(7403),
                            Fats = 36.0,
                            Protein = 108.0,
                            TotalCalories = 1801.0,
                            applicationUserId = "c4824aab-c08f-4141-86c4-082fd8bbca8c"
                        },
                        new
                        {
                            Id = 127,
                            Carbohydrates = 177.0,
                            Category = "Breakfast",
                            Date = new DateTime(2023, 4, 3, 23, 24, 6, 354, DateTimeKind.Local).AddTicks(7406),
                            Fats = 47.0,
                            Protein = 141.0,
                            TotalCalories = 1965.0,
                            applicationUserId = "2abf2679-ae98-456c-99ed-fe7ca2698c2e"
                        },
                        new
                        {
                            Id = 128,
                            Carbohydrates = 163.0,
                            Category = "Breakfast",
                            Date = new DateTime(2023, 4, 2, 23, 24, 6, 354, DateTimeKind.Local).AddTicks(7409),
                            Fats = 37.0,
                            Protein = 100.0,
                            TotalCalories = 1574.0,
                            applicationUserId = "2abf2679-ae98-456c-99ed-fe7ca2698c2e"
                        },
                        new
                        {
                            Id = 129,
                            Carbohydrates = 146.0,
                            Category = "Breakfast",
                            Date = new DateTime(2023, 4, 1, 23, 24, 6, 354, DateTimeKind.Local).AddTicks(7412),
                            Fats = 40.0,
                            Protein = 114.0,
                            TotalCalories = 1528.0,
                            applicationUserId = "2abf2679-ae98-456c-99ed-fe7ca2698c2e"
                        },
                        new
                        {
                            Id = 130,
                            Carbohydrates = 149.0,
                            Category = "Breakfast",
                            Date = new DateTime(2023, 3, 31, 23, 24, 6, 354, DateTimeKind.Local).AddTicks(7416),
                            Fats = 41.0,
                            Protein = 121.0,
                            TotalCalories = 1558.0,
                            applicationUserId = "2abf2679-ae98-456c-99ed-fe7ca2698c2e"
                        },
                        new
                        {
                            Id = 131,
                            Carbohydrates = 168.0,
                            Category = "Breakfast",
                            Date = new DateTime(2023, 3, 30, 23, 24, 6, 354, DateTimeKind.Local).AddTicks(7419),
                            Fats = 44.0,
                            Protein = 142.0,
                            TotalCalories = 1700.0,
                            applicationUserId = "2abf2679-ae98-456c-99ed-fe7ca2698c2e"
                        },
                        new
                        {
                            Id = 132,
                            Carbohydrates = 177.0,
                            Category = "Breakfast",
                            Date = new DateTime(2023, 3, 29, 23, 24, 6, 354, DateTimeKind.Local).AddTicks(7422),
                            Fats = 37.0,
                            Protein = 104.0,
                            TotalCalories = 1749.0,
                            applicationUserId = "2abf2679-ae98-456c-99ed-fe7ca2698c2e"
                        },
                        new
                        {
                            Id = 133,
                            Carbohydrates = 155.0,
                            Category = "Breakfast",
                            Date = new DateTime(2023, 3, 28, 23, 24, 6, 354, DateTimeKind.Local).AddTicks(7425),
                            Fats = 34.0,
                            Protein = 108.0,
                            TotalCalories = 1529.0,
                            applicationUserId = "2abf2679-ae98-456c-99ed-fe7ca2698c2e"
                        },
                        new
                        {
                            Id = 134,
                            Carbohydrates = 141.0,
                            Category = "Breakfast",
                            Date = new DateTime(2023, 3, 27, 23, 24, 6, 354, DateTimeKind.Local).AddTicks(7428),
                            Fats = 34.0,
                            Protein = 112.0,
                            TotalCalories = 1735.0,
                            applicationUserId = "2abf2679-ae98-456c-99ed-fe7ca2698c2e"
                        },
                        new
                        {
                            Id = 135,
                            Carbohydrates = 140.0,
                            Category = "Breakfast",
                            Date = new DateTime(2023, 3, 26, 23, 24, 6, 354, DateTimeKind.Local).AddTicks(7431),
                            Fats = 36.0,
                            Protein = 134.0,
                            TotalCalories = 1886.0,
                            applicationUserId = "2abf2679-ae98-456c-99ed-fe7ca2698c2e"
                        },
                        new
                        {
                            Id = 136,
                            Carbohydrates = 160.0,
                            Category = "Breakfast",
                            Date = new DateTime(2023, 3, 25, 23, 24, 6, 354, DateTimeKind.Local).AddTicks(7434),
                            Fats = 47.0,
                            Protein = 143.0,
                            TotalCalories = 1592.0,
                            applicationUserId = "2abf2679-ae98-456c-99ed-fe7ca2698c2e"
                        },
                        new
                        {
                            Id = 137,
                            Carbohydrates = 169.0,
                            Category = "Breakfast",
                            Date = new DateTime(2023, 3, 24, 23, 24, 6, 354, DateTimeKind.Local).AddTicks(7437),
                            Fats = 37.0,
                            Protein = 116.0,
                            TotalCalories = 1488.0,
                            applicationUserId = "2abf2679-ae98-456c-99ed-fe7ca2698c2e"
                        },
                        new
                        {
                            Id = 138,
                            Carbohydrates = 149.0,
                            Category = "Breakfast",
                            Date = new DateTime(2023, 3, 23, 23, 24, 6, 354, DateTimeKind.Local).AddTicks(7440),
                            Fats = 35.0,
                            Protein = 124.0,
                            TotalCalories = 1521.0,
                            applicationUserId = "2abf2679-ae98-456c-99ed-fe7ca2698c2e"
                        },
                        new
                        {
                            Id = 139,
                            Carbohydrates = 130.0,
                            Category = "Breakfast",
                            Date = new DateTime(2023, 3, 22, 23, 24, 6, 354, DateTimeKind.Local).AddTicks(7442),
                            Fats = 49.0,
                            Protein = 129.0,
                            TotalCalories = 1356.0,
                            applicationUserId = "2abf2679-ae98-456c-99ed-fe7ca2698c2e"
                        },
                        new
                        {
                            Id = 140,
                            Carbohydrates = 168.0,
                            Category = "Breakfast",
                            Date = new DateTime(2023, 3, 21, 23, 24, 6, 354, DateTimeKind.Local).AddTicks(7446),
                            Fats = 45.0,
                            Protein = 115.0,
                            TotalCalories = 1642.0,
                            applicationUserId = "2abf2679-ae98-456c-99ed-fe7ca2698c2e"
                        },
                        new
                        {
                            Id = 141,
                            Carbohydrates = 156.0,
                            Category = "Breakfast",
                            Date = new DateTime(2023, 4, 3, 23, 24, 6, 354, DateTimeKind.Local).AddTicks(7449),
                            Fats = 47.0,
                            Protein = 119.0,
                            TotalCalories = 1424.0,
                            applicationUserId = "5f9c85a5-0150-4a44-b5a8-e2bf0e72a6b1"
                        },
                        new
                        {
                            Id = 142,
                            Carbohydrates = 145.0,
                            Category = "Breakfast",
                            Date = new DateTime(2023, 4, 2, 23, 24, 6, 354, DateTimeKind.Local).AddTicks(7452),
                            Fats = 39.0,
                            Protein = 131.0,
                            TotalCalories = 1416.0,
                            applicationUserId = "5f9c85a5-0150-4a44-b5a8-e2bf0e72a6b1"
                        },
                        new
                        {
                            Id = 143,
                            Carbohydrates = 163.0,
                            Category = "Breakfast",
                            Date = new DateTime(2023, 4, 1, 23, 24, 6, 354, DateTimeKind.Local).AddTicks(7455),
                            Fats = 39.0,
                            Protein = 118.0,
                            TotalCalories = 1528.0,
                            applicationUserId = "5f9c85a5-0150-4a44-b5a8-e2bf0e72a6b1"
                        },
                        new
                        {
                            Id = 144,
                            Carbohydrates = 139.0,
                            Category = "Breakfast",
                            Date = new DateTime(2023, 3, 31, 23, 24, 6, 354, DateTimeKind.Local).AddTicks(7458),
                            Fats = 47.0,
                            Protein = 125.0,
                            TotalCalories = 1887.0,
                            applicationUserId = "5f9c85a5-0150-4a44-b5a8-e2bf0e72a6b1"
                        },
                        new
                        {
                            Id = 145,
                            Carbohydrates = 158.0,
                            Category = "Breakfast",
                            Date = new DateTime(2023, 3, 30, 23, 24, 6, 354, DateTimeKind.Local).AddTicks(7460),
                            Fats = 38.0,
                            Protein = 140.0,
                            TotalCalories = 1860.0,
                            applicationUserId = "5f9c85a5-0150-4a44-b5a8-e2bf0e72a6b1"
                        },
                        new
                        {
                            Id = 146,
                            Carbohydrates = 172.0,
                            Category = "Breakfast",
                            Date = new DateTime(2023, 3, 29, 23, 24, 6, 354, DateTimeKind.Local).AddTicks(7463),
                            Fats = 32.0,
                            Protein = 136.0,
                            TotalCalories = 1475.0,
                            applicationUserId = "5f9c85a5-0150-4a44-b5a8-e2bf0e72a6b1"
                        },
                        new
                        {
                            Id = 147,
                            Carbohydrates = 141.0,
                            Category = "Breakfast",
                            Date = new DateTime(2023, 3, 28, 23, 24, 6, 354, DateTimeKind.Local).AddTicks(7466),
                            Fats = 43.0,
                            Protein = 149.0,
                            TotalCalories = 1583.0,
                            applicationUserId = "5f9c85a5-0150-4a44-b5a8-e2bf0e72a6b1"
                        },
                        new
                        {
                            Id = 148,
                            Carbohydrates = 141.0,
                            Category = "Breakfast",
                            Date = new DateTime(2023, 3, 27, 23, 24, 6, 354, DateTimeKind.Local).AddTicks(7469),
                            Fats = 39.0,
                            Protein = 114.0,
                            TotalCalories = 1513.0,
                            applicationUserId = "5f9c85a5-0150-4a44-b5a8-e2bf0e72a6b1"
                        },
                        new
                        {
                            Id = 149,
                            Carbohydrates = 158.0,
                            Category = "Breakfast",
                            Date = new DateTime(2023, 3, 26, 23, 24, 6, 354, DateTimeKind.Local).AddTicks(7472),
                            Fats = 41.0,
                            Protein = 119.0,
                            TotalCalories = 1436.0,
                            applicationUserId = "5f9c85a5-0150-4a44-b5a8-e2bf0e72a6b1"
                        },
                        new
                        {
                            Id = 150,
                            Carbohydrates = 155.0,
                            Category = "Breakfast",
                            Date = new DateTime(2023, 3, 25, 23, 24, 6, 354, DateTimeKind.Local).AddTicks(7475),
                            Fats = 37.0,
                            Protein = 115.0,
                            TotalCalories = 1624.0,
                            applicationUserId = "5f9c85a5-0150-4a44-b5a8-e2bf0e72a6b1"
                        },
                        new
                        {
                            Id = 151,
                            Carbohydrates = 172.0,
                            Category = "Breakfast",
                            Date = new DateTime(2023, 3, 24, 23, 24, 6, 354, DateTimeKind.Local).AddTicks(7478),
                            Fats = 36.0,
                            Protein = 130.0,
                            TotalCalories = 1805.0,
                            applicationUserId = "5f9c85a5-0150-4a44-b5a8-e2bf0e72a6b1"
                        },
                        new
                        {
                            Id = 152,
                            Carbohydrates = 150.0,
                            Category = "Breakfast",
                            Date = new DateTime(2023, 3, 23, 23, 24, 6, 354, DateTimeKind.Local).AddTicks(7481),
                            Fats = 45.0,
                            Protein = 147.0,
                            TotalCalories = 1776.0,
                            applicationUserId = "5f9c85a5-0150-4a44-b5a8-e2bf0e72a6b1"
                        },
                        new
                        {
                            Id = 153,
                            Carbohydrates = 179.0,
                            Category = "Breakfast",
                            Date = new DateTime(2023, 3, 22, 23, 24, 6, 354, DateTimeKind.Local).AddTicks(7484),
                            Fats = 47.0,
                            Protein = 128.0,
                            TotalCalories = 1501.0,
                            applicationUserId = "5f9c85a5-0150-4a44-b5a8-e2bf0e72a6b1"
                        },
                        new
                        {
                            Id = 154,
                            Carbohydrates = 163.0,
                            Category = "Breakfast",
                            Date = new DateTime(2023, 3, 21, 23, 24, 6, 354, DateTimeKind.Local).AddTicks(7487),
                            Fats = 44.0,
                            Protein = 142.0,
                            TotalCalories = 1698.0,
                            applicationUserId = "5f9c85a5-0150-4a44-b5a8-e2bf0e72a6b1"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
